# サイズデータ投入
all_服サイズ = Size.create(name: '服サイズ')
all_靴サイズレディース = Size.create(name: '靴サイズレディース')
all_靴サイズメンズ = Size.create(name: '靴サイズメンズ')
all_ベビー服95cm = Size.create(name: 'ベビー服95cm')
all_キッズ服 = Size.create(name: 'キッズ服')
all_キッズ靴 = Size.create(name: 'キッズ靴')

all_服サイズ.children.create(name: 'XXS以下')
all_服サイズ.children.create(name: 'XS(SS)')
all_服サイズ.children.create(name: 'S')
all_服サイズ.children.create(name: 'M')
all_服サイズ.children.create(name: 'L')
all_服サイズ.children.create(name: 'XL(LL)')
all_服サイズ.children.create(name: '2XL(3L)')
all_服サイズ.children.create(name: '3XL(4L)')
all_服サイズ.children.create(name: '4XL(5L)以上')
all_服サイズ.children.create(name: 'FREE SIZE')

all_靴サイズレディース.children.create(name: '20cm以下')
all_靴サイズレディース.children.create(name: '20.5cm')
all_靴サイズレディース.children.create(name: '21cm')
all_靴サイズレディース.children.create(name: '21.5cm')
all_靴サイズレディース.children.create(name: '22cm')
all_靴サイズレディース.children.create(name: '22.5cm')
all_靴サイズレディース.children.create(name: '23cm')
all_靴サイズレディース.children.create(name: '23.5cm')
all_靴サイズレディース.children.create(name: '24cm')
all_靴サイズレディース.children.create(name: '24.5cm')
all_靴サイズレディース.children.create(name: '25cm')
all_靴サイズレディース.children.create(name: '26.5cm')
all_靴サイズレディース.children.create(name: '27cm')
all_靴サイズレディース.children.create(name: '27.5cm以上')

all_靴サイズメンズ.children.create(name: '23.5cm以下')
all_靴サイズメンズ.children.create(name: '24cm')
all_靴サイズメンズ.children.create(name: '24.5cm')
all_靴サイズメンズ.children.create(name: '25cm')
all_靴サイズメンズ.children.create(name: '25.5cm')
all_靴サイズメンズ.children.create(name: '26cm')
all_靴サイズメンズ.children.create(name: '26.5cm')
all_靴サイズメンズ.children.create(name: '27cm')
all_靴サイズメンズ.children.create(name: '27.5cm')
all_靴サイズメンズ.children.create(name: '28cm')
all_靴サイズメンズ.children.create(name: '28.5cm')
all_靴サイズメンズ.children.create(name: '29cm')
all_靴サイズメンズ.children.create(name: '29.5cm')
all_靴サイズメンズ.children.create(name: '30cm')
all_靴サイズメンズ.children.create(name: '30.5cm')
all_靴サイズメンズ.children.create(name: '31cm以上')

all_ベビー服95cm.children.create(name: '60cm')
all_ベビー服95cm.children.create(name: '70cm')
all_ベビー服95cm.children.create(name: '80cm')
all_ベビー服95cm.children.create(name: '90cm')
all_ベビー服95cm.children.create(name: '95cm')

all_キッズ服.children.create(name: "100cm")
all_キッズ服.children.create(name: "110cm")
all_キッズ服.children.create(name: "120cm")
all_キッズ服.children.create(name: "130cm")
all_キッズ服.children.create(name: "140cm")
all_キッズ服.children.create(name: "150cm")
all_キッズ服.children.create(name: "160cm")

all_キッズ靴.children.create(name: "10.5cm以下")
all_キッズ靴.children.create(name: "11cm・11.5cm")
all_キッズ靴.children.create(name: "12cm・12.5cm")
all_キッズ靴.children.create(name: "13cm・13.5cm")
all_キッズ靴.children.create(name: "14cm・14.5cm")
all_キッズ靴.children.create(name: "15cm・15.5cm")
all_キッズ靴.children.create(name: "16cm・16.5cm")
all_キッズ靴.children.create(name: "17cm以上")


# カテゴリーデータ投入
all = Category.create(name: '全て')
all_レディース = all.children.create(name: 'レディース')
all_メンズ = all.children.create(name: 'メンズ')
all_ベビーキッズ = all.children.create(name: 'ベビー・キッズ')
all_インテリア住まい小物 = all.children.create(name: 'インテリア・住まい・小物')
all_本音楽ゲーム = all.children.create(name: '本・音楽・ゲーム')
all_おもちゃホビーグッズ = all.children.create(name: 'おもちゃ・ホビー・グッズ')
all_コスメ香水美容 = all.children.create(name: 'コスメ・香水・美容')
all_家電スマホカメラ = all.children.create(name: '家電・スマホ・カメラ')
all_スポーツレジャー = all.children.create(name: 'スポーツ・レジャー')
all_ハンドメイド = all.children.create(name: 'ハンドメイド')
all_チケット = all.children.create(name: 'チケット')
all_自動車オートバイ = all.children.create(name: '自動車・オートバイ')
all_その他 = all.children.create(name: 'その他')
レディース_トップス = all_レディース.children.create(name: 'トップス', size_id: all_服サイズ.id )
レディース_ジャケットアウター = all_レディース.children.create(name: 'ジャケット/アウター', size_id: all_服サイズ.id)
レディース_パンツ = all_レディース.children.create(name: 'パンツ', size_id: all_服サイズ.id)
レディース_スカート = all_レディース.children.create(name: 'スカート', size_id: all_服サイズ.id)
レディース_ワンピース = all_レディース.children.create(name: 'ワンピース', size_id: all_服サイズ.id)
レディース_靴 = all_レディース.children.create(name: '靴', size_id: all_靴サイズレディース.id)
レディース_ルームウェアパジャマ = all_レディース.children.create(name: 'ルームウェア/パジャマ', size_id: all_服サイズ.id)
レディース_レッグウェア = all_レディース.children.create(name: 'レッグウェア')
レディース_帽子 = all_レディース.children.create(name: '帽子')
レディース_バッグ = all_レディース.children.create(name: 'バッグ')
レディース_アクセサリー = all_レディース.children.create(name: 'アクセサリー')
レディース_ヘアアクセサリー = all_レディース.children.create(name: 'ヘアアクセサリー')
レディース_小物 = all_レディース.children.create(name: '小物')
レディース_時計 = all_レディース.children.create(name: '時計')
レディース_ウィッグエクステ = all_レディース.children.create(name: 'ウィッグ/エクステ')
レディース_浴衣水着 = all_レディース.children.create(name: '浴衣/水着')
レディース_スーツフォーマルドレス = all_レディース.children.create(name: 'スーツ/フォーマル/ドレス')
レディース_マタニティ = all_レディース.children.create(name: 'マタニティ')
レディース_その他 = all_レディース.children.create(name: 'その他')
メンズ_トップス = all_メンズ.children.create(name: 'トップス', size_id: all_服サイズ.id)
メンズ_ジャケットアウター = all_メンズ.children.create(name: 'ジャケット/アウター', size_id: all_服サイズ.id)
メンズ_パンツ = all_メンズ.children.create(name: 'パンツ', size_id: all_服サイズ.id)
メンズ_靴 = all_メンズ.children.create(name: '靴', size_id: all_靴サイズメンズ.id)
メンズ_バッグ = all_メンズ.children.create(name: 'バッグ')
メンズ_スーツ = all_メンズ.children.create(name: 'スーツ')
メンズ_帽子 = all_メンズ.children.create(name: '帽子')
メンズ_アクセサリー = all_メンズ.children.create(name: 'アクセサリー')
メンズ_小物 = all_メンズ.children.create(name: '小物')
メンズ_時計 = all_メンズ.children.create(name: '時計')
メンズ_水着 = all_メンズ.children.create(name: '水着')
メンズ_レッグウェア = all_メンズ.children.create(name: 'レッグウェア')
メンズ_アンダーウェア = all_メンズ.children.create(name: 'アンダーウェア')
メンズ_その他 = all_メンズ.children.create(name: 'その他')
ベビーキッズ_ベビー服女の子用95cm = all_ベビーキッズ.children.create(name: 'ベビー服(女の子用)~95cm', size_id: all_ベビー服95cm.id)
ベビーキッズ_ベビー服男の子用95cm = all_ベビーキッズ.children.create(name: 'ベビー服(男の子用)~95cm', size_id: all_ベビー服95cm.id)
ベビーキッズ_ベビー服男女兼用95cm = all_ベビーキッズ.children.create(name: 'ベビー服(男女兼用)~95cm', size_id: all_ベビー服95cm.id)
ベビーキッズ_キッズ服女の子用100cm = all_ベビーキッズ.children.create(name: 'キッズ服(女の子用)100cm~', size_id: all_キッズ服.id)
ベビーキッズ_キッズ服男の子用100cm = all_ベビーキッズ.children.create(name: 'キッズ服(男の子用)100cm~', size_id: all_キッズ服.id)
ベビーキッズ_キッズ服男女兼用100cm = all_ベビーキッズ.children.create(name: 'キッズ服(男女兼用)100cm~', size_id: all_キッズ服.id)
ベビーキッズ_キッズ靴 = all_ベビーキッズ.children.create(name: 'キッズ靴', size_id: all_キッズ靴)
ベビーキッズ_子ども用ファッション小物 = all_ベビーキッズ.children.create(name: '子ども用ファッション小物')
ベビーキッズ_おむつトイレバス = all_ベビーキッズ.children.create(name: 'おむつ/トイレ/バス')
ベビーキッズ_外出移動用品 = all_ベビーキッズ.children.create(name: '外出/移動用品')
ベビーキッズ_授乳食事 = all_ベビーキッズ.children.create(name: '授乳/食事')
ベビーキッズ_ベビー家具寝具室内用品 = all_ベビーキッズ.children.create(name: 'ベビー家具/寝具/室内用品')
ベビーキッズ_おもちゃ = all_ベビーキッズ.children.create(name: 'おもちゃ')
ベビーキッズ_行事記念品 = all_ベビーキッズ.children.create(name: '行事/記念品')
ベビーキッズ_その他 = all_ベビーキッズ.children.create(name: 'その他')
インテリア住まい小物_キッチン食器 = all_インテリア住まい小物.children.create(name: 'キッチン/食器')
インテリア住まい小物_ベッドマットレス = all_インテリア住まい小物.children.create(name: 'ベッド/マットレス')
インテリア住まい小物_ソファソファベッド = all_インテリア住まい小物.children.create(name: 'ソファ/ソファベッド')
インテリア住まい小物_椅子チェア = all_インテリア住まい小物.children.create(name: '椅子/チェア')
インテリア住まい小物_机テーブル = all_インテリア住まい小物.children.create(name: '机/テーブル')
インテリア住まい小物_収納家具 = all_インテリア住まい小物.children.create(name: '収納家具')
インテリア住まい小物_ラグカーペットマット = all_インテリア住まい小物.children.create(name: 'ラグ/カーペット/マット')
インテリア住まい小物_カーテンブラインド = all_インテリア住まい小物.children.create(name: 'カーテン/ブラインド')
インテリア住まい小物_ライト照明 = all_インテリア住まい小物.children.create(name: 'ライト/照明')
インテリア住まい小物_寝具 = all_インテリア住まい小物.children.create(name: '寝具')
インテリア住まい小物_インテリア小物 = all_インテリア住まい小物.children.create(name: 'インテリア小物')
インテリア住まい小物_季節年中行事 = all_インテリア住まい小物.children.create(name: '季節/年中行事')
インテリア住まい小物_その他 = all_インテリア住まい小物.children.create(name: 'その他')
本音楽ゲーム_本 = all_本音楽ゲーム.children.create(name: '本')
本音楽ゲーム_漫画 = all_本音楽ゲーム.children.create(name: '漫画')
本音楽ゲーム_雑誌 = all_本音楽ゲーム.children.create(name: '雑誌')
本音楽ゲーム_CD = all_本音楽ゲーム.children.create(name: 'CD')
本音楽ゲーム_DVDブルーレイ = all_本音楽ゲーム.children.create(name: 'DVD/ブルーレイ')
本音楽ゲーム_レコード = all_本音楽ゲーム.children.create(name: 'レコード')
本音楽ゲーム_テレビゲーム = all_本音楽ゲーム.children.create(name: 'テレビゲーム')
おもちゃホビーグッズ_おもちゃ = all_おもちゃホビーグッズ.children.create(name: 'おもちゃ')
おもちゃホビーグッズ_タレントグッズ = all_おもちゃホビーグッズ.children.create(name: 'タレントグッズ')
おもちゃホビーグッズ_コミックアニメグッズ = all_おもちゃホビーグッズ.children.create(name: 'コミック/アニメグッズ')
おもちゃホビーグッズ_トレーディングカード = all_おもちゃホビーグッズ.children.create(name: 'トレーディングカード')
おもちゃホビーグッズ_フィギュア = all_おもちゃホビーグッズ.children.create(name: 'フィギュア')
おもちゃホビーグッズ_楽器器材 = all_おもちゃホビーグッズ.children.create(name: '楽器/器材')
おもちゃホビーグッズ_コレクション = all_おもちゃホビーグッズ.children.create(name: 'コレクション')
おもちゃホビーグッズ_ミリタリー = all_おもちゃホビーグッズ.children.create(name: 'ミリタリー')
おもちゃホビーグッズ_美術品 = all_おもちゃホビーグッズ.children.create(name: '美術品')
おもちゃホビーグッズ_アート用品 = all_おもちゃホビーグッズ.children.create(name: 'アート用品')
おもちゃホビーグッズ_その他 = all_おもちゃホビーグッズ.children.create(name: 'その他')
コスメ香水美容_ベースメイク = all_コスメ香水美容.children.create(name: 'ベースメイク')
コスメ香水美容_メイクアップ = all_コスメ香水美容.children.create(name: 'メイクアップ')
コスメ香水美容_ネイルケア = all_コスメ香水美容.children.create(name: 'ネイルケア')
コスメ香水美容_香水 = all_コスメ香水美容.children.create(name: '香水')
コスメ香水美容_スキンケア基礎化粧品 = all_コスメ香水美容.children.create(name: 'スキンケア/基礎化粧品')
コスメ香水美容_ヘアケア = all_コスメ香水美容.children.create(name: 'ヘアケア')
コスメ香水美容_ボディケア = all_コスメ香水美容.children.create(name: 'ボディケア')
コスメ香水美容_オーラルケア = all_コスメ香水美容.children.create(name: 'オーラルケア')
コスメ香水美容_リラクゼーション = all_コスメ香水美容.children.create(name: 'リラクゼーション')
コスメ香水美容_ダイエット = all_コスメ香水美容.children.create(name: 'ダイエット')
コスメ香水美容_その他 = all_コスメ香水美容.children.create(name: 'その他')
家電スマホカメラ_スマートフォン携帯電話 = all_家電スマホカメラ.children.create(name: 'スマートフォン/携帯電話')
家電スマホカメラ_スマホアクセサリー = all_家電スマホカメラ.children.create(name: 'スマホアクセサリー')
家電スマホカメラ_PCタブレット = all_家電スマホカメラ.children.create(name: 'PC/タブレット')
家電スマホカメラ_カメラ = all_家電スマホカメラ.children.create(name: 'カメラ')
家電スマホカメラ_テレビ映像機器 = all_家電スマホカメラ.children.create(name: 'テレビ/映像機器')
家電スマホカメラ_オーディオ機器 = all_家電スマホカメラ.children.create(name: 'オーディオ機器')
家電スマホカメラ_美容健康 = all_家電スマホカメラ.children.create(name: '美容/健康')
家電スマホカメラ_冷暖房空調 = all_家電スマホカメラ.children.create(name: '冷暖房/空調')
家電スマホカメラ_生活家電 = all_家電スマホカメラ.children.create(name: '生活家電')
家電スマホカメラ_その他 = all_家電スマホカメラ.children.create(name: 'その他')
スポーツレジャー_ゴルフ = all_スポーツレジャー.children.create(name: 'ゴルフ')
スポーツレジャー_フィッシング = all_スポーツレジャー.children.create(name: 'フィッシング')
スポーツレジャー_自転車 = all_スポーツレジャー.children.create(name: '自転車')
スポーツレジャー_トレーニングエクササイズ = all_スポーツレジャー.children.create(name: 'トレーニング/エクササイズ')
スポーツレジャー_野球 = all_スポーツレジャー.children.create(name: '野球')
スポーツレジャー_サッカーフットサル = all_スポーツレジャー.children.create(name: 'サッカー/フットサル')
スポーツレジャー_テニス = all_スポーツレジャー.children.create(name: 'テニス')
スポーツレジャー_スノーボード = all_スポーツレジャー.children.create(name: 'スノーボード')
スポーツレジャー_スキー = all_スポーツレジャー.children.create(name: 'スキー')
スポーツレジャー_その他スポーツ = all_スポーツレジャー.children.create(name: 'その他スポーツ')
スポーツレジャー_アウトドア = all_スポーツレジャー.children.create(name: 'アウトドア')
スポーツレジャー_その他 = all_スポーツレジャー.children.create(name: 'その他')
ハンドメイド_アクセサリー女性用 = all_ハンドメイド.children.create(name: 'アクセサリー(女性用)')
ハンドメイド_ファッション小物 = all_ハンドメイド.children.create(name: 'ファッション/小物')
ハンドメイド_アクセサリー時計 = all_ハンドメイド.children.create(name: 'アクセサリー/時計')
ハンドメイド_日用品インテリア = all_ハンドメイド.children.create(name: '日用品/インテリア')
ハンドメイド_趣味おもちゃ = all_ハンドメイド.children.create(name: '趣味/おもちゃ')
ハンドメイド_キッズベビー = all_ハンドメイド.children.create(name: 'キッズ/ベビー')
ハンドメイド_素材材料 = all_ハンドメイド.children.create(name: '素材/材料')
ハンドメイド_二次創作物 = all_ハンドメイド.children.create(name: '二次創作物')
ハンドメイド_その他 = all_ハンドメイド.children.create(name: 'その他')
チケット_音楽 = all_チケット.children.create(name: '音楽')
チケット_スポーツ = all_チケット.children.create(name: 'スポーツ')
チケット_演劇芸能 = all_チケット.children.create(name: '演劇/芸能')
チケット_イベント = all_チケット.children.create(name: 'イベント')
チケット_映画 = all_チケット.children.create(name: '映画')
チケット_施設利用券 = all_チケット.children.create(name: '施設利用券')
チケット_優待券割引券 = all_チケット.children.create(name: '優待券/割引券')
チケット_その他 = all_チケット.children.create(name: 'その他')
自動車オートバイ_自動車本体 = all_自動車オートバイ.children.create(name: '自動車本体')
自動車オートバイ_自動車タイヤホイール = all_自動車オートバイ.children.create(name: '自動車タイヤ/ホイール')
自動車オートバイ_自動車パーツ = all_自動車オートバイ.children.create(name: '自動車パーツ')
自動車オートバイ_自動車アクセサリー = all_自動車オートバイ.children.create(name: '自動車アクセサリー')
自動車オートバイ_オートバイ車体 = all_自動車オートバイ.children.create(name: 'オートバイ車体')
自動車オートバイ_オートバイパーツ = all_自動車オートバイ.children.create(name: 'オートバイパーツ')
自動車オートバイ_オートバイアクセサリー = all_自動車オートバイ.children.create(name: 'オートバイアクセサリー')
その他_まとめ売り = all_その他.children.create(name: 'まとめ売り')
その他_ペット用品 = all_その他.children.create(name: 'ペット用品')
その他_食品 = all_その他.children.create(name: '食品')
その他_飲料酒 = all_その他.children.create(name: '飲料/酒')
その他_日用品生活雑貨旅行 = all_その他.children.create(name: '日用品/生活雑貨/旅行')
その他_アンティークコレクション = all_その他.children.create(name: 'アンティーク/コレクション')
その他_文房具事務用品 = all_その他.children.create(name: '文房具/事務用品')
その他_事務店舗用品 = all_その他.children.create(name: '事務/店舗用品')
その他_その他 = all_その他.children.create(name: 'その他')
レディース_トップス.children.create(name: 'Tシャツ/カットソー(半袖/袖なし)')
レディース_トップス.children.create(name: 'Tシャツ/カットソー(七分/長袖)')
レディース_トップス.children.create(name: 'シャツ/ブラウス(半袖/袖なし)')
レディース_トップス.children.create(name: 'シャツ/ブラウス(七分/長袖)')
レディース_トップス.children.create(name: 'ポロシャツ')
レディース_トップス.children.create(name: 'キャミソール')
レディース_トップス.children.create(name: 'タンクトップ')
レディース_トップス.children.create(name: 'ホルターネック')
レディース_トップス.children.create(name: 'ニット/セーター')
レディース_トップス.children.create(name: 'チュニック')
レディース_トップス.children.create(name: 'カーディガン/ボレロ')
レディース_トップス.children.create(name: 'アンサンブル')
レディース_トップス.children.create(name: 'ベスト/ジレ')
レディース_トップス.children.create(name: 'パーカー')
レディース_トップス.children.create(name: 'トレーナー/スウェット')
レディース_トップス.children.create(name: 'ベアトップ/チューブトップ')
レディース_トップス.children.create(name: 'ジャージ')
レディース_トップス.children.create(name: 'その他')
レディース_ジャケットアウター.children.create(name: 'テーラードジャケット')
レディース_ジャケットアウター.children.create(name: 'ノーカラージャケット')
レディース_ジャケットアウター.children.create(name: 'Gジャン/デニムジャケット')
レディース_ジャケットアウター.children.create(name: 'レザージャケット')
レディース_ジャケットアウター.children.create(name: 'ダウンジャケット')
レディース_ジャケットアウター.children.create(name: 'ライダースジャケット')
レディース_ジャケットアウター.children.create(name: 'ミリタリージャケット')
レディース_ジャケットアウター.children.create(name: 'ダウンベスト')
レディース_ジャケットアウター.children.create(name: 'ジャンパー/ブルゾン')
レディース_ジャケットアウター.children.create(name: 'ポンチョ')
レディース_ジャケットアウター.children.create(name: 'ロングコート')
レディース_ジャケットアウター.children.create(name: 'トレンチコート')
レディース_ジャケットアウター.children.create(name: 'ダッフルコート')
レディース_ジャケットアウター.children.create(name: 'ピーコート')
レディース_ジャケットアウター.children.create(name: 'チェスターコート')
レディース_ジャケットアウター.children.create(name: 'モッズコート')
レディース_ジャケットアウター.children.create(name: 'スタジャン')
レディース_ジャケットアウター.children.create(name: '毛皮/ファーコート')
レディース_ジャケットアウター.children.create(name: 'スプリングコート')
レディース_ジャケットアウター.children.create(name: 'スカジャン')
レディース_ジャケットアウター.children.create(name: 'その他')
レディース_パンツ.children.create(name: 'デニム/ジーンズ')
レディース_パンツ.children.create(name: 'ショートパンツ')
レディース_パンツ.children.create(name: 'カジュアルパンツ')
レディース_パンツ.children.create(name: 'ハーフパンツ')
レディース_パンツ.children.create(name: 'チノパン')
レディース_パンツ.children.create(name: 'ワークパンツ/カーゴパンツ')
レディース_パンツ.children.create(name: 'クロップドパンツ')
レディース_パンツ.children.create(name: 'サロペット/オーバーオール')
レディース_パンツ.children.create(name: 'オールインワン')
レディース_パンツ.children.create(name: 'サルエルパンツ')
レディース_パンツ.children.create(name: 'ガウチョパンツ')
レディース_パンツ.children.create(name: 'その他')
レディース_スカート.children.create(name: 'ミニスカート')
レディース_スカート.children.create(name: 'ひざ丈スカート')
レディース_スカート.children.create(name: 'ロングスカート')
レディース_スカート.children.create(name: 'キュロット')
レディース_スカート.children.create(name: 'その他')
レディース_ワンピース.children.create(name: 'ミニワンピース')
レディース_ワンピース.children.create(name: 'ひざ丈ワンピース')
レディース_ワンピース.children.create(name: 'ロングワンピース')
レディース_ワンピース.children.create(name: 'その他')
レディース_靴.children.create(name: 'ハイヒール/パンプス')
レディース_靴.children.create(name: 'ブーツ')
レディース_靴.children.create(name: 'サンダル')
レディース_靴.children.create(name: 'スニーカー')
レディース_靴.children.create(name: 'ミュール')
レディース_靴.children.create(name: 'モカシン')
レディース_靴.children.create(name: 'ローファー/革靴')
レディース_靴.children.create(name: 'フラットシューズ/バレエシューズ')
レディース_靴.children.create(name: '長靴/レインシューズ')
レディース_靴.children.create(name: 'その他')
レディース_ルームウェアパジャマ.children.create(name: 'パジャマ')
レディース_ルームウェアパジャマ.children.create(name: 'ルームウェア')
レディース_レッグウェア.children.create(name: 'ソックス')
レディース_レッグウェア.children.create(name: 'スパッツ/レギンス')
レディース_レッグウェア.children.create(name: 'ストッキング/タイツ')
レディース_レッグウェア.children.create(name: 'レッグウォーマー')
レディース_レッグウェア.children.create(name: 'その他')
レディース_帽子.children.create(name: 'ニットキャップ/ビーニー')
レディース_帽子.children.create(name: 'ハット')
レディース_帽子.children.create(name: 'ハンチング/ベレー帽')
レディース_帽子.children.create(name: 'キャップ')
レディース_帽子.children.create(name: 'キャスケット')
レディース_帽子.children.create(name: '麦わら帽子')
レディース_帽子.children.create(name: 'その他')
レディース_バッグ.children.create(name: 'ハンドバッグ')
レディース_バッグ.children.create(name: 'トートバッグ')
レディース_バッグ.children.create(name: 'エコバッグ')
レディース_バッグ.children.create(name: 'リュック/バックパック')
レディース_バッグ.children.create(name: 'ボストンバッグ')
レディース_バッグ.children.create(name: 'スポーツバッグ')
レディース_バッグ.children.create(name: 'ショルダーバッグ')
レディース_バッグ.children.create(name: 'クラッチバッグ')
レディース_バッグ.children.create(name: 'ポーチ/バニティ')
レディース_バッグ.children.create(name: 'ボディバッグ/ウェストバッグ')
レディース_バッグ.children.create(name: 'マザーズバッグ')
レディース_バッグ.children.create(name: 'メッセンジャーバッグ')
レディース_バッグ.children.create(name: 'ビジネスバッグ')
レディース_バッグ.children.create(name: '旅行用バッグ/キャリーバッグ')
レディース_バッグ.children.create(name: 'ショップ袋')
レディース_バッグ.children.create(name: '和装用バッグ')
レディース_バッグ.children.create(name: 'かごバッグ')
レディース_バッグ.children.create(name: 'その他')
レディース_アクセサリー.children.create(name: 'ネックレス')
レディース_アクセサリー.children.create(name: 'ブレスレット')
レディース_アクセサリー.children.create(name: 'バングル/リストバンド')
レディース_アクセサリー.children.create(name: 'リング')
レディース_アクセサリー.children.create(name: 'ピアス(片耳用)')
レディース_アクセサリー.children.create(name: 'ピアス(両耳用)')
レディース_アクセサリー.children.create(name: 'イヤリング')
レディース_アクセサリー.children.create(name: 'アンクレット')
レディース_アクセサリー.children.create(name: 'ブローチ/コサージュ')
レディース_アクセサリー.children.create(name: 'チャーム')
レディース_アクセサリー.children.create(name: 'その他')
レディース_ヘアアクセサリー.children.create(name: 'ヘアゴム/シュシュ')
レディース_ヘアアクセサリー.children.create(name: 'ヘアバンド/カチューシャ')
レディース_ヘアアクセサリー.children.create(name: 'ヘアピン')
レディース_ヘアアクセサリー.children.create(name: 'その他')
レディース_小物.children.create(name: '長財布')
レディース_小物.children.create(name: '折り財布')
レディース_小物.children.create(name: 'コインケース/小銭入れ')
レディース_小物.children.create(name: '名刺入れ/定期入れ')
レディース_小物.children.create(name: 'キーケース')
レディース_小物.children.create(name: 'キーホルダー')
レディース_小物.children.create(name: '手袋/アームカバー')
レディース_小物.children.create(name: 'ハンカチ')
レディース_小物.children.create(name: 'ベルト')
レディース_小物.children.create(name: 'マフラー/ショール')
レディース_小物.children.create(name: 'ストール/スヌード')
レディース_小物.children.create(name: 'バンダナ/スカーフ')
レディース_小物.children.create(name: 'ネックウォーマー')
レディース_小物.children.create(name: 'サスペンダー')
レディース_小物.children.create(name: 'サングラス/メガネ')
レディース_小物.children.create(name: 'モバイルケース/カバー')
レディース_小物.children.create(name: '手帳')
レディース_小物.children.create(name: 'イヤマフラー')
レディース_小物.children.create(name: '傘')
レディース_小物.children.create(name: 'レインコート/ポンチョ')
レディース_小物.children.create(name: 'ミラー')
レディース_小物.children.create(name: 'タバコグッズ')
レディース_小物.children.create(name: 'その他')
レディース_時計.children.create(name: '腕時計(アナログ)')
レディース_時計.children.create(name: '腕時計(デジタル)')
レディース_時計.children.create(name: 'ラバーベルト')
レディース_時計.children.create(name: 'レザーベルト')
レディース_時計.children.create(name: '金属ベルト')
レディース_時計.children.create(name: 'その他')
レディース_ウィッグエクステ.children.create(name: '前髪ウィッグ')
レディース_ウィッグエクステ.children.create(name: 'ロングストレート')
レディース_ウィッグエクステ.children.create(name: 'ロングカール')
レディース_ウィッグエクステ.children.create(name: 'ショートストレート')
レディース_ウィッグエクステ.children.create(name: 'ショートカール')
レディース_ウィッグエクステ.children.create(name: 'その他')
レディース_浴衣水着.children.create(name: '浴衣')
レディース_浴衣水着.children.create(name: '着物')
レディース_浴衣水着.children.create(name: '振袖')
レディース_浴衣水着.children.create(name: '長襦袢/半襦袢')
レディース_浴衣水着.children.create(name: '水着セパレート', size_id: all_服サイズ.id)
レディース_浴衣水着.children.create(name: '水着ワンピース', size_id: all_服サイズ.id)
レディース_浴衣水着.children.create(name: '水着スポーツ用', size_id: all_服サイズ.id)
レディース_浴衣水着.children.create(name: 'その他')
レディース_スーツフォーマルドレス.children.create(name: 'スカートスーツ上下', size_id: all_服サイズ.id)
レディース_スーツフォーマルドレス.children.create(name: 'パンツスーツ上下', size_id: all_服サイズ.id)
レディース_スーツフォーマルドレス.children.create(name: 'ドレス', size_id: all_服サイズ.id)
レディース_スーツフォーマルドレス.children.create(name: 'パーティーバッグ')
レディース_スーツフォーマルドレス.children.create(name: 'シューズ')
レディース_スーツフォーマルドレス.children.create(name: 'ウェディング')
レディース_スーツフォーマルドレス.children.create(name: 'その他')
レディース_マタニティ.children.create(name: 'トップス', size_id: all_服サイズ.id)
レディース_マタニティ.children.create(name: 'アウター', size_id: all_服サイズ.id)
レディース_マタニティ.children.create(name: 'インナー', size_id: all_服サイズ.id)
レディース_マタニティ.children.create(name: 'ワンピース', size_id: all_服サイズ.id)
レディース_マタニティ.children.create(name: 'パンツ/スパッツ', size_id: all_服サイズ.id)
レディース_マタニティ.children.create(name: 'スカート', size_id: all_服サイズ.id)
レディース_マタニティ.children.create(name: 'パジャマ', size_id: all_服サイズ.id)
レディース_マタニティ.children.create(name: '授乳服', size_id: all_服サイズ.id)
レディース_マタニティ.children.create(name: 'その他')
レディース_その他.children.create(name: 'コスプレ')
レディース_その他.children.create(name: '下着')
レディース_その他.children.create(name: 'その他')
メンズ_トップス.children.create(name: 'Tシャツ/カットソー(半袖/袖なし)')
メンズ_トップス.children.create(name: 'Tシャツ/カットソー(七分/長袖)')
メンズ_トップス.children.create(name: 'シャツ')
メンズ_トップス.children.create(name: 'ポロシャツ')
メンズ_トップス.children.create(name: 'タンクトップ')
メンズ_トップス.children.create(name: 'ニット/セーター')
メンズ_トップス.children.create(name: 'パーカー')
メンズ_トップス.children.create(name: 'カーディガン')
メンズ_トップス.children.create(name: 'スウェット')
メンズ_トップス.children.create(name: 'ジャージ')
メンズ_トップス.children.create(name: 'ベスト')
メンズ_トップス.children.create(name: 'その他')
メンズ_ジャケットアウター.children.create(name: 'テーラードジャケット')
メンズ_ジャケットアウター.children.create(name: 'ノーカラージャケット')
メンズ_ジャケットアウター.children.create(name: 'Gジャン/デニムジャケット')
メンズ_ジャケットアウター.children.create(name: 'レザージャケット')
メンズ_ジャケットアウター.children.create(name: 'ダウンジャケット')
メンズ_ジャケットアウター.children.create(name: 'ライダースジャケット')
メンズ_ジャケットアウター.children.create(name: 'ミリタリージャケット')
メンズ_ジャケットアウター.children.create(name: 'ナイロンジャケット')
メンズ_ジャケットアウター.children.create(name: 'フライトジャケット')
メンズ_ジャケットアウター.children.create(name: 'ダッフルコート')
メンズ_ジャケットアウター.children.create(name: 'ピーコート')
メンズ_ジャケットアウター.children.create(name: 'ステンカラーコート')
メンズ_ジャケットアウター.children.create(name: 'トレンチコート')
メンズ_ジャケットアウター.children.create(name: 'モッズコート')
メンズ_ジャケットアウター.children.create(name: 'チェスターコート')
メンズ_ジャケットアウター.children.create(name: 'スタジャン')
メンズ_ジャケットアウター.children.create(name: 'スカジャン')
メンズ_ジャケットアウター.children.create(name: 'ブルゾン')
メンズ_ジャケットアウター.children.create(name: 'マウンテンパーカー')
メンズ_ジャケットアウター.children.create(name: 'ダウンベスト')
メンズ_ジャケットアウター.children.create(name: 'ポンチョ')
メンズ_ジャケットアウター.children.create(name: 'カバーオール')
メンズ_ジャケットアウター.children.create(name: 'その他')
メンズ_パンツ.children.create(name: 'デニム/ジーンズ')
メンズ_パンツ.children.create(name: 'ワークパンツ/カーゴパンツ')
メンズ_パンツ.children.create(name: 'スラックス')
メンズ_パンツ.children.create(name: 'チノパン')
メンズ_パンツ.children.create(name: 'ショートパンツ')
メンズ_パンツ.children.create(name: 'ペインターパンツ')
メンズ_パンツ.children.create(name: 'サルエルパンツ')
メンズ_パンツ.children.create(name: 'オーバーオール')
メンズ_パンツ.children.create(name: 'その他')
メンズ_靴.children.create(name: 'スニーカー')
メンズ_靴.children.create(name: 'サンダル')
メンズ_靴.children.create(name: 'ブーツ')
メンズ_靴.children.create(name: 'モカシン')
メンズ_靴.children.create(name: 'ドレス/ビジネス')
メンズ_靴.children.create(name: '長靴/レインシューズ')
メンズ_靴.children.create(name: 'デッキシューズ')
メンズ_靴.children.create(name: 'その他')
メンズ_バッグ.children.create(name: 'ショルダーバッグ')
メンズ_バッグ.children.create(name: 'トートバッグ')
メンズ_バッグ.children.create(name: 'ボストンバッグ')
メンズ_バッグ.children.create(name: 'リュック/バックパック')
メンズ_バッグ.children.create(name: 'ウエストポーチ')
メンズ_バッグ.children.create(name: 'ボディーバッグ')
メンズ_バッグ.children.create(name: 'ドラムバッグ')
メンズ_バッグ.children.create(name: 'ビジネスバッグ')
メンズ_バッグ.children.create(name: 'トラベルバッグ')
メンズ_バッグ.children.create(name: 'メッセンジャーバッグ')
メンズ_バッグ.children.create(name: 'エコバッグ')
メンズ_バッグ.children.create(name: 'その他')
メンズ_スーツ.children.create(name: 'スーツジャケット', size_id: all_服サイズ.id)
メンズ_スーツ.children.create(name: 'スーツベスト', size_id: all_服サイズ.id)
メンズ_スーツ.children.create(name: 'スラックス', size_id: all_服サイズ.id)
メンズ_スーツ.children.create(name: 'セットアップ', size_id: all_服サイズ.id)
メンズ_スーツ.children.create(name: 'その他')
メンズ_帽子.children.create(name: 'キャップ')
メンズ_帽子.children.create(name: 'ハット')
メンズ_帽子.children.create(name: 'ニットキャップ/ビーニー')
メンズ_帽子.children.create(name: 'ハンチング/ベレー帽')
メンズ_帽子.children.create(name: 'キャスケット')
メンズ_帽子.children.create(name: 'サンバイザー')
メンズ_帽子.children.create(name: 'その他')
メンズ_アクセサリー.children.create(name: 'ネックレス')
メンズ_アクセサリー.children.create(name: 'ブレスレット')
メンズ_アクセサリー.children.create(name: 'バングル/リストバンド')
メンズ_アクセサリー.children.create(name: 'リング')
メンズ_アクセサリー.children.create(name: 'ピアス(片耳用)')
メンズ_アクセサリー.children.create(name: 'ピアス(両耳用)')
メンズ_アクセサリー.children.create(name: 'アンクレット')
メンズ_アクセサリー.children.create(name: 'その他')
メンズ_小物.children.create(name: '長財布')
メンズ_小物.children.create(name: '折り財布')
メンズ_小物.children.create(name: 'マネークリップ')
メンズ_小物.children.create(name: 'コインケース/小銭入れ')
メンズ_小物.children.create(name: '名刺入れ/定期入れ')
メンズ_小物.children.create(name: 'キーケース')
メンズ_小物.children.create(name: 'キーホルダー')
メンズ_小物.children.create(name: 'ネクタイ')
メンズ_小物.children.create(name: '手袋')
メンズ_小物.children.create(name: 'ハンカチ')
メンズ_小物.children.create(name: 'ベルト')
メンズ_小物.children.create(name: 'マフラー')
メンズ_小物.children.create(name: 'ストール')
メンズ_小物.children.create(name: 'バンダナ')
メンズ_小物.children.create(name: 'ネックウォーマー')
メンズ_小物.children.create(name: 'サスペンダー')
メンズ_小物.children.create(name: 'ウォレットチェーン')
メンズ_小物.children.create(name: 'サングラス/メガネ')
メンズ_小物.children.create(name: 'モバイルケース/カバー')
メンズ_小物.children.create(name: '手帳')
メンズ_小物.children.create(name: 'ストラップ')
メンズ_小物.children.create(name: 'ネクタイピン')
メンズ_小物.children.create(name: 'カフリンクス')
メンズ_小物.children.create(name: 'イヤマフラー')
メンズ_小物.children.create(name: '傘')
メンズ_小物.children.create(name: 'レインコート')
メンズ_小物.children.create(name: 'ミラー')
メンズ_小物.children.create(name: 'タバコグッズ')
メンズ_小物.children.create(name: 'その他')
メンズ_時計.children.create(name: '腕時計(アナログ)')
メンズ_時計.children.create(name: '腕時計(デジタル)')
メンズ_時計.children.create(name: 'ラバーベルト')
メンズ_時計.children.create(name: 'レザーベルト')
メンズ_時計.children.create(name: '金属ベルト')
メンズ_時計.children.create(name: 'その他')
メンズ_水着.children.create(name: '一般水着', size_id: all_服サイズ.id)
メンズ_水着.children.create(name: 'スポーツ用', size_id: all_服サイズ.id)
メンズ_水着.children.create(name: 'アクセサリー')
メンズ_水着.children.create(name: 'その他')
メンズ_レッグウェア.children.create(name: 'ソックス')
メンズ_レッグウェア.children.create(name: 'レギンス/スパッツ')
メンズ_レッグウェア.children.create(name: 'レッグウォーマー')
メンズ_レッグウェア.children.create(name: 'その他')
メンズ_アンダーウェア.children.create(name: 'トランクス', size_id: all_服サイズ.id)
メンズ_アンダーウェア.children.create(name: 'ボクサーパンツ', size_id: all_服サイズ.id)
メンズ_アンダーウェア.children.create(name: 'その他')
ベビーキッズ_ベビー服女の子用95cm.children.create(name: 'トップス')
ベビーキッズ_ベビー服女の子用95cm.children.create(name: 'アウター')
ベビーキッズ_ベビー服女の子用95cm.children.create(name: 'パンツ')
ベビーキッズ_ベビー服女の子用95cm.children.create(name: 'スカート')
ベビーキッズ_ベビー服女の子用95cm.children.create(name: 'ワンピース')
ベビーキッズ_ベビー服女の子用95cm.children.create(name: 'ベビードレス')
ベビーキッズ_ベビー服女の子用95cm.children.create(name: 'おくるみ')
ベビーキッズ_ベビー服女の子用95cm.children.create(name: '下着/肌着')
ベビーキッズ_ベビー服女の子用95cm.children.create(name: 'パジャマ')
ベビーキッズ_ベビー服女の子用95cm.children.create(name: 'ロンパース')
ベビーキッズ_ベビー服女の子用95cm.children.create(name: 'その他')
ベビーキッズ_ベビー服男の子用95cm.children.create(name: 'トップス')
ベビーキッズ_ベビー服男の子用95cm.children.create(name: 'アウター')
ベビーキッズ_ベビー服男の子用95cm.children.create(name: 'パンツ')
ベビーキッズ_ベビー服男の子用95cm.children.create(name: 'おくるみ')
ベビーキッズ_ベビー服男の子用95cm.children.create(name: '下着/肌着')
ベビーキッズ_ベビー服男の子用95cm.children.create(name: 'パジャマ')
ベビーキッズ_ベビー服男の子用95cm.children.create(name: 'ロンパース')
ベビーキッズ_ベビー服男の子用95cm.children.create(name: 'その他')
ベビーキッズ_ベビー服男女兼用95cm.children.create(name: 'トップス')
ベビーキッズ_ベビー服男女兼用95cm.children.create(name: 'アウター')
ベビーキッズ_ベビー服男女兼用95cm.children.create(name: 'パンツ')
ベビーキッズ_ベビー服男女兼用95cm.children.create(name: 'おくるみ')
ベビーキッズ_ベビー服男女兼用95cm.children.create(name: '下着/肌着')
ベビーキッズ_ベビー服男女兼用95cm.children.create(name: 'パジャマ')
ベビーキッズ_ベビー服男女兼用95cm.children.create(name: 'ロンパース')
ベビーキッズ_ベビー服男女兼用95cm.children.create(name: 'その他')
ベビーキッズ_キッズ服女の子用100cm.children.create(name: 'コート')
ベビーキッズ_キッズ服女の子用100cm.children.create(name: 'ジャケット/上着')
ベビーキッズ_キッズ服女の子用100cm.children.create(name: 'トップス(Tシャツ/カットソー)')
ベビーキッズ_キッズ服女の子用100cm.children.create(name: 'トップス(トレーナー)')
ベビーキッズ_キッズ服女の子用100cm.children.create(name: 'トップス(チュニック)')
ベビーキッズ_キッズ服女の子用100cm.children.create(name: 'トップス(タンクトップ)')
ベビーキッズ_キッズ服女の子用100cm.children.create(name: 'トップス(その他)')
ベビーキッズ_キッズ服女の子用100cm.children.create(name: 'スカート')
ベビーキッズ_キッズ服女の子用100cm.children.create(name: 'パンツ')
ベビーキッズ_キッズ服女の子用100cm.children.create(name: 'ワンピース')
ベビーキッズ_キッズ服女の子用100cm.children.create(name: 'セットアップ')
ベビーキッズ_キッズ服女の子用100cm.children.create(name: 'パジャマ')
ベビーキッズ_キッズ服女の子用100cm.children.create(name: 'フォーマル/ドレス')
ベビーキッズ_キッズ服女の子用100cm.children.create(name: '和服')
ベビーキッズ_キッズ服女の子用100cm.children.create(name: '浴衣')
ベビーキッズ_キッズ服女の子用100cm.children.create(name: '甚平')
ベビーキッズ_キッズ服女の子用100cm.children.create(name: '水着')
ベビーキッズ_キッズ服女の子用100cm.children.create(name: 'その他')
ベビーキッズ_キッズ服男の子用100cm.children.create(name: 'コート')
ベビーキッズ_キッズ服男の子用100cm.children.create(name: 'ジャケット/上着')
ベビーキッズ_キッズ服男の子用100cm.children.create(name: 'トップス(Tシャツ/カットソー)')
ベビーキッズ_キッズ服男の子用100cm.children.create(name: 'トップス(トレーナー)')
ベビーキッズ_キッズ服男の子用100cm.children.create(name: 'トップス(その他)')
ベビーキッズ_キッズ服男の子用100cm.children.create(name: 'パンツ')
ベビーキッズ_キッズ服男の子用100cm.children.create(name: 'セットアップ')
ベビーキッズ_キッズ服男の子用100cm.children.create(name: 'パジャマ')
ベビーキッズ_キッズ服男の子用100cm.children.create(name: 'フォーマル/ドレス')
ベビーキッズ_キッズ服男の子用100cm.children.create(name: '和服')
ベビーキッズ_キッズ服男の子用100cm.children.create(name: '浴衣')
ベビーキッズ_キッズ服男の子用100cm.children.create(name: '甚平')
ベビーキッズ_キッズ服男の子用100cm.children.create(name: '水着')
ベビーキッズ_キッズ服男の子用100cm.children.create(name: 'その他')
ベビーキッズ_キッズ服男女兼用100cm.children.create(name: 'コート')
ベビーキッズ_キッズ服男女兼用100cm.children.create(name: 'ジャケット/上着')
ベビーキッズ_キッズ服男女兼用100cm.children.create(name: 'トップス(Tシャツ/カットソー)')
ベビーキッズ_キッズ服男女兼用100cm.children.create(name: 'トップス(トレーナー)')
ベビーキッズ_キッズ服男女兼用100cm.children.create(name: 'トップス(その他)')
ベビーキッズ_キッズ服男女兼用100cm.children.create(name: 'ボトムス')
ベビーキッズ_キッズ服男女兼用100cm.children.create(name: 'パジャマ')
ベビーキッズ_キッズ服男女兼用100cm.children.create(name: 'その他')
ベビーキッズ_キッズ靴.children.create(name: 'スニーカー')
ベビーキッズ_キッズ靴.children.create(name: 'サンダル')
ベビーキッズ_キッズ靴.children.create(name: 'ブーツ')
ベビーキッズ_キッズ靴.children.create(name: '長靴')
ベビーキッズ_キッズ靴.children.create(name: 'その他')
ベビーキッズ_子ども用ファッション小物.children.create(name: '靴下/スパッツ')
ベビーキッズ_子ども用ファッション小物.children.create(name: '帽子')
ベビーキッズ_子ども用ファッション小物.children.create(name: 'エプロン')
ベビーキッズ_子ども用ファッション小物.children.create(name: 'サスペンダー')
ベビーキッズ_子ども用ファッション小物.children.create(name: 'タイツ')
ベビーキッズ_子ども用ファッション小物.children.create(name: 'ハンカチ')
ベビーキッズ_子ども用ファッション小物.children.create(name: 'バンダナ')
ベビーキッズ_子ども用ファッション小物.children.create(name: 'ベルト')
ベビーキッズ_子ども用ファッション小物.children.create(name: 'マフラー')
ベビーキッズ_子ども用ファッション小物.children.create(name: '傘')
ベビーキッズ_子ども用ファッション小物.children.create(name: '手袋')
ベビーキッズ_子ども用ファッション小物.children.create(name: 'スタイ')
ベビーキッズ_子ども用ファッション小物.children.create(name: 'バッグ')
ベビーキッズ_子ども用ファッション小物.children.create(name: 'その他')
ベビーキッズ_おむつトイレバス.children.create(name: 'おむつ用品')
ベビーキッズ_おむつトイレバス.children.create(name: 'おまる/補助便座')
ベビーキッズ_おむつトイレバス.children.create(name: 'トレーニングパンツ')
ベビーキッズ_おむつトイレバス.children.create(name: 'ベビーバス')
ベビーキッズ_おむつトイレバス.children.create(name: 'お風呂用品')
ベビーキッズ_おむつトイレバス.children.create(name: 'その他')
ベビーキッズ_外出移動用品.children.create(name: 'ベビーカー')
ベビーキッズ_外出移動用品.children.create(name: '抱っこひも/スリング')
ベビーキッズ_外出移動用品.children.create(name: 'チャイルドシート')
ベビーキッズ_外出移動用品.children.create(name: 'その他')
ベビーキッズ_授乳食事.children.create(name: 'ミルク')
ベビーキッズ_授乳食事.children.create(name: 'ベビーフード')
ベビーキッズ_授乳食事.children.create(name: 'ベビー用食器')
ベビーキッズ_授乳食事.children.create(name: 'その他')
ベビーキッズ_ベビー家具寝具室内用品.children.create(name: 'ベッド')
ベビーキッズ_ベビー家具寝具室内用品.children.create(name: '布団/毛布')
ベビーキッズ_ベビー家具寝具室内用品.children.create(name: 'イス')
ベビーキッズ_ベビー家具寝具室内用品.children.create(name: 'たんす')
ベビーキッズ_ベビー家具寝具室内用品.children.create(name: 'その他')
ベビーキッズ_おもちゃ.children.create(name: 'おふろのおもちゃ')
ベビーキッズ_おもちゃ.children.create(name: 'がらがら')
ベビーキッズ_おもちゃ.children.create(name: 'オルゴール')
ベビーキッズ_おもちゃ.children.create(name: 'ベビージム')
ベビーキッズ_おもちゃ.children.create(name: '手押し車/カタカタ')
ベビーキッズ_おもちゃ.children.create(name: '知育玩具')
ベビーキッズ_おもちゃ.children.create(name: 'その他')
ベビーキッズ_行事記念品.children.create(name: 'お宮参り用品')
ベビーキッズ_行事記念品.children.create(name: 'お食い初め用品')
ベビーキッズ_行事記念品.children.create(name: 'アルバム')
ベビーキッズ_行事記念品.children.create(name: '手形/足形')
ベビーキッズ_行事記念品.children.create(name: 'その他')
ベビーキッズ_その他.children.create(name: '母子手帳用品')
ベビーキッズ_その他.children.create(name: 'その他')
インテリア住まい小物_キッチン食器.children.create(name: '食器')
インテリア住まい小物_キッチン食器.children.create(name: '調理器具')
インテリア住まい小物_キッチン食器.children.create(name: '収納/キッチン雑貨')
インテリア住まい小物_キッチン食器.children.create(name: '弁当用品')
インテリア住まい小物_キッチン食器.children.create(name: 'カトラリー(スプーン等)')
インテリア住まい小物_キッチン食器.children.create(name: 'テーブル用品')
インテリア住まい小物_キッチン食器.children.create(name: '容器')
インテリア住まい小物_キッチン食器.children.create(name: 'エプロン')
インテリア住まい小物_キッチン食器.children.create(name: 'アルコールグッズ')
インテリア住まい小物_キッチン食器.children.create(name: '浄水機')
インテリア住まい小物_キッチン食器.children.create(name: 'その他')
インテリア住まい小物_ベッドマットレス.children.create(name: 'セミシングルベッド')
インテリア住まい小物_ベッドマットレス.children.create(name: 'シングルベッド')
インテリア住まい小物_ベッドマットレス.children.create(name: 'セミダブルベッド')
インテリア住まい小物_ベッドマットレス.children.create(name: 'ダブルベッド')
インテリア住まい小物_ベッドマットレス.children.create(name: 'ワイドダブルベッド')
インテリア住まい小物_ベッドマットレス.children.create(name: 'クイーンベッド')
インテリア住まい小物_ベッドマットレス.children.create(name: 'キングベッド')
インテリア住まい小物_ベッドマットレス.children.create(name: '脚付きマットレスベッド')
インテリア住まい小物_ベッドマットレス.children.create(name: 'マットレス')
インテリア住まい小物_ベッドマットレス.children.create(name: 'すのこベッド')
インテリア住まい小物_ベッドマットレス.children.create(name: 'ロフトベッド/システムベッド')
インテリア住まい小物_ベッドマットレス.children.create(name: '簡易ベッド/折りたたみベッド')
インテリア住まい小物_ベッドマットレス.children.create(name: '収納付き')
インテリア住まい小物_ベッドマットレス.children.create(name: 'その他')
インテリア住まい小物_ソファソファベッド.children.create(name: 'ソファセット')
インテリア住まい小物_ソファソファベッド.children.create(name: 'シングルソファ')
インテリア住まい小物_ソファソファベッド.children.create(name: 'ラブソファ')
インテリア住まい小物_ソファソファベッド.children.create(name: 'トリプルソファ')
インテリア住まい小物_ソファソファベッド.children.create(name: 'オットマン')
インテリア住まい小物_ソファソファベッド.children.create(name: 'コーナーソファ')
インテリア住まい小物_ソファソファベッド.children.create(name: 'ビーズソファ/クッションソファ')
インテリア住まい小物_ソファソファベッド.children.create(name: 'ローソファ/フロアソファ')
インテリア住まい小物_ソファソファベッド.children.create(name: 'ソファベッド')
インテリア住まい小物_ソファソファベッド.children.create(name: '応接セット')
インテリア住まい小物_ソファソファベッド.children.create(name: 'ソファカバー')
インテリア住まい小物_ソファソファベッド.children.create(name: 'リクライニングソファ')
インテリア住まい小物_ソファソファベッド.children.create(name: 'その他')
インテリア住まい小物_椅子チェア.children.create(name: '一般')
インテリア住まい小物_椅子チェア.children.create(name: 'スツール')
インテリア住まい小物_椅子チェア.children.create(name: 'ダイニングチェア')
インテリア住まい小物_椅子チェア.children.create(name: 'ハイバックチェア')
インテリア住まい小物_椅子チェア.children.create(name: 'ロッキングチェア')
インテリア住まい小物_椅子チェア.children.create(name: '座椅子')
インテリア住まい小物_椅子チェア.children.create(name: '折り畳みイス')
インテリア住まい小物_椅子チェア.children.create(name: 'デスクチェア')
インテリア住まい小物_椅子チェア.children.create(name: 'その他')
インテリア住まい小物_机テーブル.children.create(name: 'こたつ')
インテリア住まい小物_机テーブル.children.create(name: 'カウンターテーブル')
インテリア住まい小物_机テーブル.children.create(name: 'サイドテーブル')
インテリア住まい小物_机テーブル.children.create(name: 'センターテーブル')
インテリア住まい小物_机テーブル.children.create(name: 'ダイニングテーブル')
インテリア住まい小物_机テーブル.children.create(name: '座卓/ちゃぶ台')
インテリア住まい小物_机テーブル.children.create(name: 'アウトドア用')
インテリア住まい小物_机テーブル.children.create(name: 'パソコン用')
インテリア住まい小物_机テーブル.children.create(name: '事務机/学習机')
インテリア住まい小物_机テーブル.children.create(name: 'その他')
インテリア住まい小物_収納家具.children.create(name: 'リビング収納')
インテリア住まい小物_収納家具.children.create(name: 'キッチン収納')
インテリア住まい小物_収納家具.children.create(name: '玄関/屋外収納')
インテリア住まい小物_収納家具.children.create(name: 'バス/トイレ収納')
インテリア住まい小物_収納家具.children.create(name: '本収納')
インテリア住まい小物_収納家具.children.create(name: '本/CD/DVD収納')
インテリア住まい小物_収納家具.children.create(name: '洋服タンス/押入れ収納')
インテリア住まい小物_収納家具.children.create(name: '電話台/ファックス台')
インテリア住まい小物_収納家具.children.create(name: 'ドレッサー/鏡台')
インテリア住まい小物_収納家具.children.create(name: '棚/ラック')
インテリア住まい小物_収納家具.children.create(name: 'ケース/ボックス')
インテリア住まい小物_収納家具.children.create(name: 'その他')
インテリア住まい小物_ラグカーペットマット.children.create(name: 'ラグ')
インテリア住まい小物_ラグカーペットマット.children.create(name: 'カーペット')
インテリア住まい小物_ラグカーペットマット.children.create(name: 'ホットカーペット')
インテリア住まい小物_ラグカーペットマット.children.create(name: '玄関/キッチンマット')
インテリア住まい小物_ラグカーペットマット.children.create(name: 'トイレ/バスマット')
インテリア住まい小物_ラグカーペットマット.children.create(name: 'その他')
インテリア住まい小物_カーテンブラインド.children.create(name: 'カーテン')
インテリア住まい小物_カーテンブラインド.children.create(name: 'ブラインド')
インテリア住まい小物_カーテンブラインド.children.create(name: 'ロールスクリーン')
インテリア住まい小物_カーテンブラインド.children.create(name: 'のれん')
インテリア住まい小物_カーテンブラインド.children.create(name: 'その他')
インテリア住まい小物_ライト照明.children.create(name: '蛍光灯/電球')
インテリア住まい小物_ライト照明.children.create(name: '天井照明')
インテリア住まい小物_ライト照明.children.create(name: 'フロアスタンド')
インテリア住まい小物_ライト照明.children.create(name: 'その他')
インテリア住まい小物_寝具.children.create(name: '布団/毛布')
インテリア住まい小物_寝具.children.create(name: '枕')
インテリア住まい小物_寝具.children.create(name: 'シーツ/カバー')
インテリア住まい小物_寝具.children.create(name: 'その他')
インテリア住まい小物_インテリア小物.children.create(name: 'ごみ箱')
インテリア住まい小物_インテリア小物.children.create(name: 'ウェルカムボード')
インテリア住まい小物_インテリア小物.children.create(name: 'オルゴール')
インテリア住まい小物_インテリア小物.children.create(name: 'クッション')
インテリア住まい小物_インテリア小物.children.create(name: 'クッションカバー')
インテリア住まい小物_インテリア小物.children.create(name: 'スリッパラック')
インテリア住まい小物_インテリア小物.children.create(name: 'ティッシュボックス')
インテリア住まい小物_インテリア小物.children.create(name: 'バスケット/かご')
インテリア住まい小物_インテリア小物.children.create(name: 'フォトフレーム')
インテリア住まい小物_インテリア小物.children.create(name: 'マガジンラック')
インテリア住まい小物_インテリア小物.children.create(name: 'モビール')
インテリア住まい小物_インテリア小物.children.create(name: '花瓶')
インテリア住まい小物_インテリア小物.children.create(name: '灰皿')
インテリア住まい小物_インテリア小物.children.create(name: '傘立て')
インテリア住まい小物_インテリア小物.children.create(name: '小物入れ')
インテリア住まい小物_インテリア小物.children.create(name: '置時計')
インテリア住まい小物_インテリア小物.children.create(name: '掛時計/柱時計')
インテリア住まい小物_インテリア小物.children.create(name: '鏡(立て掛け式)')
インテリア住まい小物_インテリア小物.children.create(name: '鏡(壁掛け式)')
インテリア住まい小物_インテリア小物.children.create(name: '置物')
インテリア住まい小物_インテリア小物.children.create(name: '風鈴')
インテリア住まい小物_インテリア小物.children.create(name: '植物/観葉植物')
インテリア住まい小物_インテリア小物.children.create(name: 'その他')
インテリア住まい小物_季節年中行事.children.create(name: '正月')
インテリア住まい小物_季節年中行事.children.create(name: '成人式')
インテリア住まい小物_季節年中行事.children.create(name: 'バレンタインデー')
インテリア住まい小物_季節年中行事.children.create(name: 'ひな祭り')
インテリア住まい小物_季節年中行事.children.create(name: '子どもの日')
インテリア住まい小物_季節年中行事.children.create(name: '母の日')
インテリア住まい小物_季節年中行事.children.create(name: '父の日')
インテリア住まい小物_季節年中行事.children.create(name: 'サマーギフト/お中元')
インテリア住まい小物_季節年中行事.children.create(name: '夏/夏休み')
インテリア住まい小物_季節年中行事.children.create(name: 'ハロウィン')
インテリア住まい小物_季節年中行事.children.create(name: '敬老の日')
インテリア住まい小物_季節年中行事.children.create(name: '七五三')
インテリア住まい小物_季節年中行事.children.create(name: 'お歳暮')
インテリア住まい小物_季節年中行事.children.create(name: 'クリスマス')
インテリア住まい小物_季節年中行事.children.create(name: '冬一般')
インテリア住まい小物_季節年中行事.children.create(name: 'その他')
本音楽ゲーム_本.children.create(name: '文学/小説')
本音楽ゲーム_本.children.create(name: '人文/社会')
本音楽ゲーム_本.children.create(name: 'ノンフィクション/教養')
本音楽ゲーム_本.children.create(name: '地図/旅行ガイド')
本音楽ゲーム_本.children.create(name: 'ビジネス/経済')
本音楽ゲーム_本.children.create(name: '健康/医学')
本音楽ゲーム_本.children.create(name: 'コンピュータ/IT')
本音楽ゲーム_本.children.create(name: '趣味/スポーツ/実用')
本音楽ゲーム_本.children.create(name: '住まい/暮らし/子育て')
本音楽ゲーム_本.children.create(name: 'アート/エンタメ')
本音楽ゲーム_本.children.create(name: '洋書')
本音楽ゲーム_本.children.create(name: '絵本')
本音楽ゲーム_本.children.create(name: '参考書')
本音楽ゲーム_本.children.create(name: 'その他')
本音楽ゲーム_漫画.children.create(name: '全巻セット')
本音楽ゲーム_漫画.children.create(name: '少年漫画')
本音楽ゲーム_漫画.children.create(name: '少女漫画')
本音楽ゲーム_漫画.children.create(name: '青年漫画')
本音楽ゲーム_漫画.children.create(name: '女性漫画')
本音楽ゲーム_漫画.children.create(name: '同人誌')
本音楽ゲーム_漫画.children.create(name: 'その他')
本音楽ゲーム_雑誌.children.create(name: 'アート/エンタメ/ホビー')
本音楽ゲーム_雑誌.children.create(name: 'ファッション')
本音楽ゲーム_雑誌.children.create(name: 'ニュース/総合')
本音楽ゲーム_雑誌.children.create(name: '趣味/スポーツ')
本音楽ゲーム_雑誌.children.create(name: 'その他')
本音楽ゲーム_CD.children.create(name: '邦楽')
本音楽ゲーム_CD.children.create(name: '洋楽')
本音楽ゲーム_CD.children.create(name: 'アニメ')
本音楽ゲーム_CD.children.create(name: 'クラシック')
本音楽ゲーム_CD.children.create(name: 'K-POP/アジア')
本音楽ゲーム_CD.children.create(name: 'キッズ/ファミリー')
本音楽ゲーム_CD.children.create(name: 'その他')
本音楽ゲーム_DVDブルーレイ.children.create(name: '外国映画')
本音楽ゲーム_DVDブルーレイ.children.create(name: '日本映画')
本音楽ゲーム_DVDブルーレイ.children.create(name: 'アニメ')
本音楽ゲーム_DVDブルーレイ.children.create(name: 'TVドラマ')
本音楽ゲーム_DVDブルーレイ.children.create(name: 'ミュージック')
本音楽ゲーム_DVDブルーレイ.children.create(name: 'お笑い/バラエティ')
本音楽ゲーム_DVDブルーレイ.children.create(name: 'スポーツ/フィットネス')
本音楽ゲーム_DVDブルーレイ.children.create(name: 'キッズ/ファミリー')
本音楽ゲーム_DVDブルーレイ.children.create(name: 'その他')
本音楽ゲーム_レコード.children.create(name: '邦楽')
本音楽ゲーム_レコード.children.create(name: '洋楽')
本音楽ゲーム_レコード.children.create(name: 'その他')
本音楽ゲーム_テレビゲーム.children.create(name: '家庭用ゲーム本体')
本音楽ゲーム_テレビゲーム.children.create(name: '家庭用ゲームソフト')
本音楽ゲーム_テレビゲーム.children.create(name: '携帯用ゲーム本体')
本音楽ゲーム_テレビゲーム.children.create(name: '携帯用ゲームソフト')
本音楽ゲーム_テレビゲーム.children.create(name: 'PCゲーム')
本音楽ゲーム_テレビゲーム.children.create(name: 'その他')
おもちゃホビーグッズ_おもちゃ.children.create(name: 'キャラクターグッズ')
おもちゃホビーグッズ_おもちゃ.children.create(name: 'ぬいぐるみ')
おもちゃホビーグッズ_おもちゃ.children.create(name: '小物/アクセサリー')
おもちゃホビーグッズ_おもちゃ.children.create(name: '模型/プラモデル')
おもちゃホビーグッズ_おもちゃ.children.create(name: 'ミニカー')
おもちゃホビーグッズ_おもちゃ.children.create(name: 'トイラジコン')
おもちゃホビーグッズ_おもちゃ.children.create(name: 'プラモデル')
おもちゃホビーグッズ_おもちゃ.children.create(name: 'ホビーラジコン')
おもちゃホビーグッズ_おもちゃ.children.create(name: '鉄道模型')
おもちゃホビーグッズ_おもちゃ.children.create(name: 'その他')
おもちゃホビーグッズ_タレントグッズ.children.create(name: 'アイドル')
おもちゃホビーグッズ_タレントグッズ.children.create(name: 'ミュージシャン')
おもちゃホビーグッズ_タレントグッズ.children.create(name: 'タレント/お笑い芸人')
おもちゃホビーグッズ_タレントグッズ.children.create(name: 'スポーツ選手')
おもちゃホビーグッズ_タレントグッズ.children.create(name: 'その他')
おもちゃホビーグッズ_コミックアニメグッズ.children.create(name: 'ストラップ')
おもちゃホビーグッズ_コミックアニメグッズ.children.create(name: 'キーホルダー')
おもちゃホビーグッズ_コミックアニメグッズ.children.create(name: 'バッジ')
おもちゃホビーグッズ_コミックアニメグッズ.children.create(name: 'カード')
おもちゃホビーグッズ_コミックアニメグッズ.children.create(name: 'クリアファイル')
おもちゃホビーグッズ_コミックアニメグッズ.children.create(name: 'ポスター')
おもちゃホビーグッズ_コミックアニメグッズ.children.create(name: 'タオル')
おもちゃホビーグッズ_コミックアニメグッズ.children.create(name: 'その他')
おもちゃホビーグッズ_トレーディングカード.children.create(name: '遊戯王')
おもちゃホビーグッズ_トレーディングカード.children.create(name: 'マジック：ザ・ギャザリング')
おもちゃホビーグッズ_トレーディングカード.children.create(name: 'ポケモンカードゲーム')
おもちゃホビーグッズ_トレーディングカード.children.create(name: 'デュエルマスターズ')
おもちゃホビーグッズ_トレーディングカード.children.create(name: 'バトルスピリッツ')
おもちゃホビーグッズ_トレーディングカード.children.create(name: 'プリパラ')
おもちゃホビーグッズ_トレーディングカード.children.create(name: 'アイカツ')
おもちゃホビーグッズ_トレーディングカード.children.create(name: 'カードファイト!! ヴァンガード')
おもちゃホビーグッズ_トレーディングカード.children.create(name: 'ヴァイスシュヴァルツ')
おもちゃホビーグッズ_トレーディングカード.children.create(name: 'プロ野球オーナーズリーグ')
おもちゃホビーグッズ_トレーディングカード.children.create(name: 'ベースボールヒーローズ')
おもちゃホビーグッズ_トレーディングカード.children.create(name: 'ドラゴンボール')
おもちゃホビーグッズ_トレーディングカード.children.create(name: 'スリーブ')
おもちゃホビーグッズ_トレーディングカード.children.create(name: 'その他')
おもちゃホビーグッズ_フィギュア.children.create(name: 'コミック/アニメ')
おもちゃホビーグッズ_フィギュア.children.create(name: '特撮')
おもちゃホビーグッズ_フィギュア.children.create(name: 'ゲームキャラクター')
おもちゃホビーグッズ_フィギュア.children.create(name: 'SF/ファンタジー/ホラー')
おもちゃホビーグッズ_フィギュア.children.create(name: 'アメコミ')
おもちゃホビーグッズ_フィギュア.children.create(name: 'スポーツ')
おもちゃホビーグッズ_フィギュア.children.create(name: 'ミリタリー')
おもちゃホビーグッズ_フィギュア.children.create(name: 'その他')
おもちゃホビーグッズ_楽器器材.children.create(name: 'エレキギター')
おもちゃホビーグッズ_楽器器材.children.create(name: 'アコースティックギター')
おもちゃホビーグッズ_楽器器材.children.create(name: 'ベース')
おもちゃホビーグッズ_楽器器材.children.create(name: 'エフェクター')
おもちゃホビーグッズ_楽器器材.children.create(name: 'アンプ')
おもちゃホビーグッズ_楽器器材.children.create(name: '弦楽器')
おもちゃホビーグッズ_楽器器材.children.create(name: '管楽器')
おもちゃホビーグッズ_楽器器材.children.create(name: '鍵盤楽器')
おもちゃホビーグッズ_楽器器材.children.create(name: '打楽器')
おもちゃホビーグッズ_楽器器材.children.create(name: '和楽器')
おもちゃホビーグッズ_楽器器材.children.create(name: '楽譜/スコア')
おもちゃホビーグッズ_楽器器材.children.create(name: 'レコーディング/PA機器')
おもちゃホビーグッズ_楽器器材.children.create(name: 'DJ機器')
おもちゃホビーグッズ_楽器器材.children.create(name: 'DTM/DAW')
おもちゃホビーグッズ_楽器器材.children.create(name: 'その他')
おもちゃホビーグッズ_コレクション.children.create(name: '武具')
おもちゃホビーグッズ_コレクション.children.create(name: '使用済切手/官製はがき')
おもちゃホビーグッズ_コレクション.children.create(name: '旧貨幣/金貨/銀貨/記念硬貨')
おもちゃホビーグッズ_コレクション.children.create(name: '印刷物')
おもちゃホビーグッズ_コレクション.children.create(name: 'ノベルティグッズ')
おもちゃホビーグッズ_コレクション.children.create(name: 'その他')
おもちゃホビーグッズ_ミリタリー.children.create(name: 'トイガン')
おもちゃホビーグッズ_ミリタリー.children.create(name: '個人装備')
おもちゃホビーグッズ_ミリタリー.children.create(name: 'その他')
おもちゃホビーグッズ_美術品.children.create(name: '陶芸')
おもちゃホビーグッズ_美術品.children.create(name: 'ガラス')
おもちゃホビーグッズ_美術品.children.create(name: '漆芸')
おもちゃホビーグッズ_美術品.children.create(name: '金属工芸')
おもちゃホビーグッズ_美術品.children.create(name: '絵画/タペストリ')
おもちゃホビーグッズ_美術品.children.create(name: '版画')
おもちゃホビーグッズ_美術品.children.create(name: '彫刻/オブジェクト')
おもちゃホビーグッズ_美術品.children.create(name: '書')
おもちゃホビーグッズ_美術品.children.create(name: '写真')
おもちゃホビーグッズ_美術品.children.create(name: 'その他')
おもちゃホビーグッズ_アート用品.children.create(name: '画材')
おもちゃホビーグッズ_アート用品.children.create(name: '額縁')
おもちゃホビーグッズ_アート用品.children.create(name: 'その他')
おもちゃホビーグッズ_その他.children.create(name: 'トランプ/UNO')
おもちゃホビーグッズ_その他.children.create(name: 'カルタ/百人一首')
おもちゃホビーグッズ_その他.children.create(name: 'ダーツ')
おもちゃホビーグッズ_その他.children.create(name: 'ビリヤード')
おもちゃホビーグッズ_その他.children.create(name: '麻雀')
おもちゃホビーグッズ_その他.children.create(name: 'パズル/ジグソーパズル')
おもちゃホビーグッズ_その他.children.create(name: '囲碁/将棋')
おもちゃホビーグッズ_その他.children.create(name: 'オセロ/チェス')
おもちゃホビーグッズ_その他.children.create(name: '人生ゲーム')
おもちゃホビーグッズ_その他.children.create(name: '野球/サッカーゲーム')
おもちゃホビーグッズ_その他.children.create(name: 'スポーツ')
おもちゃホビーグッズ_その他.children.create(name: '三輪車/乗り物')
おもちゃホビーグッズ_その他.children.create(name: 'ヨーヨー')
おもちゃホビーグッズ_その他.children.create(name: '模型製作用品')
おもちゃホビーグッズ_その他.children.create(name: '鉄道')
おもちゃホビーグッズ_その他.children.create(name: '航空機')
おもちゃホビーグッズ_その他.children.create(name: 'アマチュア無線')
おもちゃホビーグッズ_その他.children.create(name: 'パチンコ/パチスロ')
おもちゃホビーグッズ_その他.children.create(name: 'その他')
コスメ香水美容_ベースメイク.children.create(name: 'ファンデーション')
コスメ香水美容_ベースメイク.children.create(name: '化粧下地')
コスメ香水美容_ベースメイク.children.create(name: 'コントロールカラー')
コスメ香水美容_ベースメイク.children.create(name: 'BBクリーム')
コスメ香水美容_ベースメイク.children.create(name: 'CCクリーム')
コスメ香水美容_ベースメイク.children.create(name: 'コンシーラー')
コスメ香水美容_ベースメイク.children.create(name: 'フェイスパウダー')
コスメ香水美容_ベースメイク.children.create(name: 'トライアルセット/サンプル')
コスメ香水美容_ベースメイク.children.create(name: 'その他')
コスメ香水美容_メイクアップ.children.create(name: 'アイシャドウ')
コスメ香水美容_メイクアップ.children.create(name: '口紅')
コスメ香水美容_メイクアップ.children.create(name: 'リップグロス')
コスメ香水美容_メイクアップ.children.create(name: 'リップライナー')
コスメ香水美容_メイクアップ.children.create(name: 'チーク')
コスメ香水美容_メイクアップ.children.create(name: 'フェイスカラー')
コスメ香水美容_メイクアップ.children.create(name: 'マスカラ')
コスメ香水美容_メイクアップ.children.create(name: 'アイライナー')
コスメ香水美容_メイクアップ.children.create(name: 'つけまつげ')
コスメ香水美容_メイクアップ.children.create(name: 'アイブロウペンシル')
コスメ香水美容_メイクアップ.children.create(name: 'パウダーアイブロウ')
コスメ香水美容_メイクアップ.children.create(name: '眉マスカラ')
コスメ香水美容_メイクアップ.children.create(name: 'トライアルセット/サンプル')
コスメ香水美容_メイクアップ.children.create(name: 'メイク道具/化粧小物')
コスメ香水美容_メイクアップ.children.create(name: '美顔用品/美顔ローラー')
コスメ香水美容_メイクアップ.children.create(name: 'その他')
コスメ香水美容_ネイルケア.children.create(name: 'ネイルカラー')
コスメ香水美容_ネイルケア.children.create(name: 'カラージェル')
コスメ香水美容_ネイルケア.children.create(name: 'ネイルベースコート/トップコート')
コスメ香水美容_ネイルケア.children.create(name: 'ネイルアート用品')
コスメ香水美容_ネイルケア.children.create(name: 'ネイルパーツ')
コスメ香水美容_ネイルケア.children.create(name: 'ネイルチップ/付け爪')
コスメ香水美容_ネイルケア.children.create(name: '手入れ用具')
コスメ香水美容_ネイルケア.children.create(name: '除光液')
コスメ香水美容_ネイルケア.children.create(name: 'その他')
コスメ香水美容_香水.children.create(name: '香水(女性用)')
コスメ香水美容_香水.children.create(name: '香水(男性用)')
コスメ香水美容_香水.children.create(name: 'ユニセックス')
コスメ香水美容_香水.children.create(name: 'ボディミスト')
コスメ香水美容_香水.children.create(name: 'その他')
コスメ香水美容_スキンケア基礎化粧品.children.create(name: '化粧水/ローション')
コスメ香水美容_スキンケア基礎化粧品.children.create(name: '乳液/ミルク')
コスメ香水美容_スキンケア基礎化粧品.children.create(name: '美容液')
コスメ香水美容_スキンケア基礎化粧品.children.create(name: 'フェイスクリーム')
コスメ香水美容_スキンケア基礎化粧品.children.create(name: '洗顔料')
コスメ香水美容_スキンケア基礎化粧品.children.create(name: 'クレンジング/メイク落とし')
コスメ香水美容_スキンケア基礎化粧品.children.create(name: 'パック/フェイスマスク')
コスメ香水美容_スキンケア基礎化粧品.children.create(name: 'ジェル/ゲル')
コスメ香水美容_スキンケア基礎化粧品.children.create(name: 'ブースター/導入液')
コスメ香水美容_スキンケア基礎化粧品.children.create(name: 'アイケア')
コスメ香水美容_スキンケア基礎化粧品.children.create(name: 'リップケア')
コスメ香水美容_スキンケア基礎化粧品.children.create(name: 'トライアルセット/サンプル')
コスメ香水美容_スキンケア基礎化粧品.children.create(name: '洗顔グッズ')
コスメ香水美容_スキンケア基礎化粧品.children.create(name: 'その他')
コスメ香水美容_ヘアケア.children.create(name: 'シャンプー')
コスメ香水美容_ヘアケア.children.create(name: 'トリートメント')
コスメ香水美容_ヘアケア.children.create(name: 'コンディショナー')
コスメ香水美容_ヘアケア.children.create(name: 'リンス')
コスメ香水美容_ヘアケア.children.create(name: 'スタイリング剤')
コスメ香水美容_ヘアケア.children.create(name: 'カラーリング剤')
コスメ香水美容_ヘアケア.children.create(name: 'ブラシ')
コスメ香水美容_ヘアケア.children.create(name: 'その他')
コスメ香水美容_ボディケア.children.create(name: 'オイル/クリーム')
コスメ香水美容_ボディケア.children.create(name: 'ハンドクリーム')
コスメ香水美容_ボディケア.children.create(name: 'ローション')
コスメ香水美容_ボディケア.children.create(name: '日焼け止め/サンオイル')
コスメ香水美容_ボディケア.children.create(name: 'ボディソープ')
コスメ香水美容_ボディケア.children.create(name: '入浴剤')
コスメ香水美容_ボディケア.children.create(name: '制汗/デオドラント')
コスメ香水美容_ボディケア.children.create(name: 'フットケア')
コスメ香水美容_ボディケア.children.create(name: 'その他')
コスメ香水美容_オーラルケア.children.create(name: '口臭防止/エチケット用品')
コスメ香水美容_オーラルケア.children.create(name: '歯ブラシ')
コスメ香水美容_オーラルケア.children.create(name: 'その他')
コスメ香水美容_リラクゼーション.children.create(name: 'エッセンシャルオイル')
コスメ香水美容_リラクゼーション.children.create(name: '芳香器')
コスメ香水美容_リラクゼーション.children.create(name: 'お香/香炉')
コスメ香水美容_リラクゼーション.children.create(name: 'キャンドル')
コスメ香水美容_リラクゼーション.children.create(name: 'リラクゼーショングッズ')
コスメ香水美容_リラクゼーション.children.create(name: 'その他')
コスメ香水美容_ダイエット.children.create(name: 'ダイエット食品')
コスメ香水美容_ダイエット.children.create(name: 'エクササイズ用品')
コスメ香水美容_ダイエット.children.create(name: '体重計')
コスメ香水美容_ダイエット.children.create(name: '体脂肪計')
コスメ香水美容_ダイエット.children.create(name: 'その他')
コスメ香水美容_その他.children.create(name: '健康用品')
コスメ香水美容_その他.children.create(name: '看護/介護用品')
コスメ香水美容_その他.children.create(name: '救急/衛生用品')
コスメ香水美容_その他.children.create(name: 'その他')
家電スマホカメラ_スマートフォン携帯電話.children.create(name: 'スマートフォン本体')
家電スマホカメラ_スマートフォン携帯電話.children.create(name: 'バッテリー/充電器')
家電スマホカメラ_スマートフォン携帯電話.children.create(name: '携帯電話本体')
家電スマホカメラ_スマートフォン携帯電話.children.create(name: 'PHS本体')
家電スマホカメラ_スマートフォン携帯電話.children.create(name: 'その他')
家電スマホカメラ_スマホアクセサリー.children.create(name: 'Android用ケース')
家電スマホカメラ_スマホアクセサリー.children.create(name: 'iPhone用ケース')
家電スマホカメラ_スマホアクセサリー.children.create(name: 'カバー')
家電スマホカメラ_スマホアクセサリー.children.create(name: 'イヤホンジャック')
家電スマホカメラ_スマホアクセサリー.children.create(name: 'ストラップ')
家電スマホカメラ_スマホアクセサリー.children.create(name: 'フィルム')
家電スマホカメラ_スマホアクセサリー.children.create(name: '自撮り棒')
家電スマホカメラ_スマホアクセサリー.children.create(name: 'その他')
家電スマホカメラ_PCタブレット.children.create(name: 'タブレット')
家電スマホカメラ_PCタブレット.children.create(name: 'ノートPC')
家電スマホカメラ_PCタブレット.children.create(name: 'デスクトップ型PC')
家電スマホカメラ_PCタブレット.children.create(name: 'ディスプレイ')
家電スマホカメラ_PCタブレット.children.create(name: '電子ブックリーダー')
家電スマホカメラ_PCタブレット.children.create(name: 'PC周辺機器')
家電スマホカメラ_PCタブレット.children.create(name: 'PCパーツ')
家電スマホカメラ_PCタブレット.children.create(name: 'その他')
家電スマホカメラ_カメラ.children.create(name: 'デジタルカメラ')
家電スマホカメラ_カメラ.children.create(name: 'ビデオカメラ')
家電スマホカメラ_カメラ.children.create(name: 'レンズ(単焦点)')
家電スマホカメラ_カメラ.children.create(name: 'レンズ(ズーム)')
家電スマホカメラ_カメラ.children.create(name: 'フィルムカメラ')
家電スマホカメラ_カメラ.children.create(name: '防犯カメラ')
家電スマホカメラ_カメラ.children.create(name: 'その他')
家電スマホカメラ_テレビ映像機器.children.create(name: 'テレビ')
家電スマホカメラ_テレビ映像機器.children.create(name: 'プロジェクター')
家電スマホカメラ_テレビ映像機器.children.create(name: 'ブルーレイレコーダー')
家電スマホカメラ_テレビ映像機器.children.create(name: 'DVDレコーダー')
家電スマホカメラ_テレビ映像機器.children.create(name: 'ブルーレイプレーヤー')
家電スマホカメラ_テレビ映像機器.children.create(name: 'DVDプレーヤー')
家電スマホカメラ_テレビ映像機器.children.create(name: '映像用ケーブル')
家電スマホカメラ_テレビ映像機器.children.create(name: 'その他')
家電スマホカメラ_オーディオ機器.children.create(name: 'ポータブルプレーヤー')
家電スマホカメラ_オーディオ機器.children.create(name: 'イヤフォン')
家電スマホカメラ_オーディオ機器.children.create(name: 'ヘッドフォン')
家電スマホカメラ_オーディオ機器.children.create(name: 'アンプ')
家電スマホカメラ_オーディオ機器.children.create(name: 'スピーカー')
家電スマホカメラ_オーディオ機器.children.create(name: 'ケーブル/シールド')
家電スマホカメラ_オーディオ機器.children.create(name: 'ラジオ')
家電スマホカメラ_オーディオ機器.children.create(name: 'その他')
家電スマホカメラ_美容健康.children.create(name: 'ヘアドライヤー')
家電スマホカメラ_美容健康.children.create(name: 'ヘアアイロン')
家電スマホカメラ_美容健康.children.create(name: '美容機器')
家電スマホカメラ_美容健康.children.create(name: '電気シェーバー')
家電スマホカメラ_美容健康.children.create(name: '電動歯ブラシ')
家電スマホカメラ_美容健康.children.create(name: 'その他')
家電スマホカメラ_冷暖房空調.children.create(name: 'エアコン')
家電スマホカメラ_冷暖房空調.children.create(name: '空気清浄器')
家電スマホカメラ_冷暖房空調.children.create(name: '加湿器')
家電スマホカメラ_冷暖房空調.children.create(name: '扇風機')
家電スマホカメラ_冷暖房空調.children.create(name: '除湿機')
家電スマホカメラ_冷暖房空調.children.create(name: 'ファンヒーター')
家電スマホカメラ_冷暖房空調.children.create(name: '電気ヒーター')
家電スマホカメラ_冷暖房空調.children.create(name: 'オイルヒーター')
家電スマホカメラ_冷暖房空調.children.create(name: 'ストーブ')
家電スマホカメラ_冷暖房空調.children.create(name: 'ホットカーペット')
家電スマホカメラ_冷暖房空調.children.create(name: 'こたつ')
家電スマホカメラ_冷暖房空調.children.create(name: '電気毛布')
家電スマホカメラ_冷暖房空調.children.create(name: 'その他')
家電スマホカメラ_生活家電.children.create(name: '冷蔵庫')
家電スマホカメラ_生活家電.children.create(name: '洗濯機')
家電スマホカメラ_生活家電.children.create(name: '炊飯器')
家電スマホカメラ_生活家電.children.create(name: '電子レンジ/オーブン')
家電スマホカメラ_生活家電.children.create(name: '調理機器')
家電スマホカメラ_生活家電.children.create(name: 'アイロン')
家電スマホカメラ_生活家電.children.create(name: '掃除機')
家電スマホカメラ_生活家電.children.create(name: 'エスプレッソマシン')
家電スマホカメラ_生活家電.children.create(name: 'コーヒーメーカー')
家電スマホカメラ_生活家電.children.create(name: '衣類乾燥機')
家電スマホカメラ_生活家電.children.create(name: 'その他')
家電スマホカメラ_その他.children.create(name: 'その他')
スポーツレジャー_ゴルフ.children.create(name: 'クラブ')
スポーツレジャー_ゴルフ.children.create(name: 'ウエア(男性用)')
スポーツレジャー_ゴルフ.children.create(name: 'ウエア(女性用)')
スポーツレジャー_ゴルフ.children.create(name: 'バッグ')
スポーツレジャー_ゴルフ.children.create(name: 'シューズ(男性用)')
スポーツレジャー_ゴルフ.children.create(name: 'シューズ(女性用)')
スポーツレジャー_ゴルフ.children.create(name: 'アクセサリー')
スポーツレジャー_ゴルフ.children.create(name: 'その他')
スポーツレジャー_フィッシング.children.create(name: 'ロッド')
スポーツレジャー_フィッシング.children.create(name: 'リール')
スポーツレジャー_フィッシング.children.create(name: 'ルアー用品')
スポーツレジャー_フィッシング.children.create(name: 'ウエア')
スポーツレジャー_フィッシング.children.create(name: '釣り糸/ライン')
スポーツレジャー_フィッシング.children.create(name: 'その他')
スポーツレジャー_自転車.children.create(name: '自転車本体')
スポーツレジャー_自転車.children.create(name: 'ウエア')
スポーツレジャー_自転車.children.create(name: 'パーツ')
スポーツレジャー_自転車.children.create(name: 'アクセサリー')
スポーツレジャー_自転車.children.create(name: 'バッグ')
スポーツレジャー_自転車.children.create(name: '工具/メンテナンス')
スポーツレジャー_自転車.children.create(name: 'その他')
スポーツレジャー_トレーニングエクササイズ.children.create(name: 'ランニング')
スポーツレジャー_トレーニングエクササイズ.children.create(name: 'ウォーキング')
スポーツレジャー_トレーニングエクササイズ.children.create(name: 'ヨガ')
スポーツレジャー_トレーニングエクササイズ.children.create(name: 'トレーニング用品')
スポーツレジャー_トレーニングエクササイズ.children.create(name: 'その他')
スポーツレジャー_野球.children.create(name: 'ウェア')
スポーツレジャー_野球.children.create(name: 'シューズ')
スポーツレジャー_野球.children.create(name: 'グローブ')
スポーツレジャー_野球.children.create(name: 'バット')
スポーツレジャー_野球.children.create(name: 'アクセサリー')
スポーツレジャー_野球.children.create(name: '防具')
スポーツレジャー_野球.children.create(name: '練習機器')
スポーツレジャー_野球.children.create(name: '記念グッズ')
スポーツレジャー_野球.children.create(name: '応援グッズ')
スポーツレジャー_野球.children.create(name: 'その他')
スポーツレジャー_サッカーフットサル.children.create(name: 'ウェア')
スポーツレジャー_サッカーフットサル.children.create(name: 'シューズ')
スポーツレジャー_サッカーフットサル.children.create(name: 'ボール')
スポーツレジャー_サッカーフットサル.children.create(name: 'アクセサリー')
スポーツレジャー_サッカーフットサル.children.create(name: '記念グッズ')
スポーツレジャー_サッカーフットサル.children.create(name: '応援グッズ')
スポーツレジャー_サッカーフットサル.children.create(name: 'その他')
スポーツレジャー_テニス.children.create(name: 'ラケット(硬式用)')
スポーツレジャー_テニス.children.create(name: 'ラケット(軟式用)')
スポーツレジャー_テニス.children.create(name: 'ウェア')
スポーツレジャー_テニス.children.create(name: 'シューズ')
スポーツレジャー_テニス.children.create(name: 'ボール')
スポーツレジャー_テニス.children.create(name: 'アクセサリー')
スポーツレジャー_テニス.children.create(name: '記念グッズ')
スポーツレジャー_テニス.children.create(name: '応援グッズ')
スポーツレジャー_テニス.children.create(name: 'その他')
スポーツレジャー_スノーボード.children.create(name: 'ボード')
スポーツレジャー_スノーボード.children.create(name: 'バインディング')
スポーツレジャー_スノーボード.children.create(name: 'ブーツ(男性用)')
スポーツレジャー_スノーボード.children.create(name: 'ブーツ(女性用)')
スポーツレジャー_スノーボード.children.create(name: 'ブーツ(子ども用)')
スポーツレジャー_スノーボード.children.create(name: 'ウエア/装備(男性用)')
スポーツレジャー_スノーボード.children.create(name: 'ウエア/装備(女性用)')
スポーツレジャー_スノーボード.children.create(name: 'ウエア/装備(子ども用)')
スポーツレジャー_スノーボード.children.create(name: 'アクセサリー')
スポーツレジャー_スノーボード.children.create(name: 'バッグ')
スポーツレジャー_スノーボード.children.create(name: 'その他')
スポーツレジャー_スキー.children.create(name: '板')
スポーツレジャー_スキー.children.create(name: 'ブーツ(男性用)')
スポーツレジャー_スキー.children.create(name: 'ブーツ(女性用)')
スポーツレジャー_スキー.children.create(name: 'ブーツ(子ども用)')
スポーツレジャー_スキー.children.create(name: 'ビンディング')
スポーツレジャー_スキー.children.create(name: 'ウエア(男性用)')
スポーツレジャー_スキー.children.create(name: 'ウエア(女性用)')
スポーツレジャー_スキー.children.create(name: 'ウエア(子ども用)')
スポーツレジャー_スキー.children.create(name: 'ストック')
スポーツレジャー_スキー.children.create(name: 'その他')
スポーツレジャー_その他スポーツ.children.create(name: 'ダンス/バレエ')
スポーツレジャー_その他スポーツ.children.create(name: 'サーフィン')
スポーツレジャー_その他スポーツ.children.create(name: 'バスケットボール')
スポーツレジャー_その他スポーツ.children.create(name: 'バドミントン')
スポーツレジャー_その他スポーツ.children.create(name: 'バレーボール')
スポーツレジャー_その他スポーツ.children.create(name: 'スケートボード')
スポーツレジャー_その他スポーツ.children.create(name: '陸上競技')
スポーツレジャー_その他スポーツ.children.create(name: 'ラグビー')
スポーツレジャー_その他スポーツ.children.create(name: 'アメリカンフットボール')
スポーツレジャー_その他スポーツ.children.create(name: 'ボクシング')
スポーツレジャー_その他スポーツ.children.create(name: 'ボウリング')
スポーツレジャー_その他スポーツ.children.create(name: 'その他')
スポーツレジャー_アウトドア.children.create(name: 'テント/タープ')
スポーツレジャー_アウトドア.children.create(name: 'ライト/ランタン')
スポーツレジャー_アウトドア.children.create(name: '寝袋/寝具')
スポーツレジャー_アウトドア.children.create(name: 'テーブル/チェア')
スポーツレジャー_アウトドア.children.create(name: 'ストーブ/コンロ')
スポーツレジャー_アウトドア.children.create(name: '調理器具')
スポーツレジャー_アウトドア.children.create(name: '食器')
スポーツレジャー_アウトドア.children.create(name: '登山用品')
スポーツレジャー_アウトドア.children.create(name: 'その他')
スポーツレジャー_その他.children.create(name: '旅行用品')
スポーツレジャー_その他.children.create(name: 'その他')
ハンドメイド_アクセサリー女性用.children.create(name: 'ピアス')
ハンドメイド_アクセサリー女性用.children.create(name: 'イヤリング')
ハンドメイド_アクセサリー女性用.children.create(name: 'ネックレス')
ハンドメイド_アクセサリー女性用.children.create(name: 'ブレスレット')
ハンドメイド_アクセサリー女性用.children.create(name: 'リング')
ハンドメイド_アクセサリー女性用.children.create(name: 'チャーム')
ハンドメイド_アクセサリー女性用.children.create(name: 'ヘアゴム')
ハンドメイド_アクセサリー女性用.children.create(name: 'アンクレット')
ハンドメイド_アクセサリー女性用.children.create(name: 'その他')
ハンドメイド_ファッション小物.children.create(name: 'バッグ(女性用)')
ハンドメイド_ファッション小物.children.create(name: 'バッグ(男性用)')
ハンドメイド_ファッション小物.children.create(name: '財布(女性用)')
ハンドメイド_ファッション小物.children.create(name: '財布(男性用)')
ハンドメイド_ファッション小物.children.create(name: 'ファッション雑貨')
ハンドメイド_ファッション小物.children.create(name: 'その他')
ハンドメイド_アクセサリー時計.children.create(name: 'アクセサリー(男性用)')
ハンドメイド_アクセサリー時計.children.create(name: '時計(女性用)')
ハンドメイド_アクセサリー時計.children.create(name: '時計(男性用)')
ハンドメイド_アクセサリー時計.children.create(name: 'その他')
ハンドメイド_日用品インテリア.children.create(name: 'キッチン用品')
ハンドメイド_日用品インテリア.children.create(name: '家具')
ハンドメイド_日用品インテリア.children.create(name: '文房具')
ハンドメイド_日用品インテリア.children.create(name: 'アート/写真')
ハンドメイド_日用品インテリア.children.create(name: 'アロマ/キャンドル')
ハンドメイド_日用品インテリア.children.create(name: 'フラワー/ガーデン')
ハンドメイド_日用品インテリア.children.create(name: 'その他')
ハンドメイド_趣味おもちゃ.children.create(name: 'クラフト/布製品')
ハンドメイド_趣味おもちゃ.children.create(name: 'おもちゃ/人形')
ハンドメイド_趣味おもちゃ.children.create(name: 'その他')
ハンドメイド_キッズベビー.children.create(name: 'ファッション雑貨')
ハンドメイド_キッズベビー.children.create(name: 'スタイ/よだれかけ')
ハンドメイド_キッズベビー.children.create(name: '外出用品')
ハンドメイド_キッズベビー.children.create(name: 'ネームタグ')
ハンドメイド_キッズベビー.children.create(name: 'その他')
ハンドメイド_素材材料.children.create(name: '各種パーツ')
ハンドメイド_素材材料.children.create(name: '生地/糸')
ハンドメイド_素材材料.children.create(name: '型紙/パターン')
ハンドメイド_素材材料.children.create(name: 'その他')
ハンドメイド_二次創作物.children.create(name: 'Ingress')
ハンドメイド_二次創作物.children.create(name: 'クリエイターズ宇宙兄弟')
チケット_音楽.children.create(name: '男性アイドル')
チケット_音楽.children.create(name: '女性アイドル')
チケット_音楽.children.create(name: '韓流')
チケット_音楽.children.create(name: '国内アーティスト')
チケット_音楽.children.create(name: '海外アーティスト')
チケット_音楽.children.create(name: '音楽フェス')
チケット_音楽.children.create(name: '声優/アニメ')
チケット_音楽.children.create(name: 'その他')
チケット_スポーツ.children.create(name: 'サッカー')
チケット_スポーツ.children.create(name: '野球')
チケット_スポーツ.children.create(name: 'テニス')
チケット_スポーツ.children.create(name: '格闘技/プロレス')
チケット_スポーツ.children.create(name: '相撲/武道')
チケット_スポーツ.children.create(name: 'ゴルフ')
チケット_スポーツ.children.create(name: 'バレーボール')
チケット_スポーツ.children.create(name: 'バスケットボール')
チケット_スポーツ.children.create(name: 'モータースポーツ')
チケット_スポーツ.children.create(name: 'ウィンタースポーツ')
チケット_スポーツ.children.create(name: 'その他')
チケット_演劇芸能.children.create(name: 'ミュージカル')
チケット_演劇芸能.children.create(name: '演劇')
チケット_演劇芸能.children.create(name: '伝統芸能')
チケット_演劇芸能.children.create(name: '落語')
チケット_演劇芸能.children.create(name: 'お笑い')
チケット_演劇芸能.children.create(name: 'オペラ')
チケット_演劇芸能.children.create(name: 'サーカス')
チケット_演劇芸能.children.create(name: 'バレエ')
チケット_演劇芸能.children.create(name: 'その他')
チケット_イベント.children.create(name: '声優/アニメ')
チケット_イベント.children.create(name: 'キッズ/ファミリー')
チケット_イベント.children.create(name: 'トークショー/講演会')
チケット_イベント.children.create(name: 'その他')
チケット_映画.children.create(name: '邦画')
チケット_映画.children.create(name: '洋画')
チケット_映画.children.create(name: 'その他')
チケット_施設利用券.children.create(name: '遊園地/テーマパーク')
チケット_施設利用券.children.create(name: '美術館/博物館')
チケット_施設利用券.children.create(name: 'スキー場')
チケット_施設利用券.children.create(name: 'ゴルフ場')
チケット_施設利用券.children.create(name: 'フィットネスクラブ')
チケット_施設利用券.children.create(name: 'プール')
チケット_施設利用券.children.create(name: 'ボウリング場')
チケット_施設利用券.children.create(name: '水族館')
チケット_施設利用券.children.create(name: '動物園')
チケット_施設利用券.children.create(name: 'その他')
チケット_優待券割引券.children.create(name: 'ショッピング')
チケット_優待券割引券.children.create(name: 'レストラン/食事券')
チケット_優待券割引券.children.create(name: 'フード/ドリンク券')
チケット_優待券割引券.children.create(name: '宿泊券')
チケット_優待券割引券.children.create(name: 'その他')
自動車オートバイ_自動車本体.children.create(name: '国内自動車本体')
自動車オートバイ_自動車本体.children.create(name: '外国自動車本体')
自動車オートバイ_自動車タイヤホイール.children.create(name: 'タイヤ/ホイールセット')
自動車オートバイ_自動車タイヤホイール.children.create(name: 'タイヤ')
自動車オートバイ_自動車タイヤホイール.children.create(name: 'ホイール')
自動車オートバイ_自動車タイヤホイール.children.create(name: 'その他')
自動車オートバイ_自動車パーツ.children.create(name: 'サスペンション')
自動車オートバイ_自動車パーツ.children.create(name: 'ブレーキ')
自動車オートバイ_自動車パーツ.children.create(name: '外装、エアロパーツ')
自動車オートバイ_自動車パーツ.children.create(name: 'ライト')
自動車オートバイ_自動車パーツ.children.create(name: '内装品、シート')
自動車オートバイ_自動車パーツ.children.create(name: 'ステアリング')
自動車オートバイ_自動車パーツ.children.create(name: 'マフラー・排気系')
自動車オートバイ_自動車パーツ.children.create(name: 'エンジン、過給器、冷却装置')
自動車オートバイ_自動車パーツ.children.create(name: 'クラッチ、ミッション、駆動系')
自動車オートバイ_自動車パーツ.children.create(name: '電装品')
自動車オートバイ_自動車パーツ.children.create(name: '補強パーツ')
自動車オートバイ_自動車パーツ.children.create(name: '汎用パーツ')
自動車オートバイ_自動車パーツ.children.create(name: '外国自動車用パーツ')
自動車オートバイ_自動車パーツ.children.create(name: 'その他')
自動車オートバイ_自動車アクセサリー.children.create(name: '車内アクセサリー')
自動車オートバイ_自動車アクセサリー.children.create(name: 'カーナビ')
自動車オートバイ_自動車アクセサリー.children.create(name: 'カーオーディオ')
自動車オートバイ_自動車アクセサリー.children.create(name: '車外アクセサリー')
自動車オートバイ_自動車アクセサリー.children.create(name: 'メンテナンス用品')
自動車オートバイ_自動車アクセサリー.children.create(name: 'チャイルドシート')
自動車オートバイ_自動車アクセサリー.children.create(name: 'ドライブレコーダー')
自動車オートバイ_自動車アクセサリー.children.create(name: 'レーダー探知機')
自動車オートバイ_自動車アクセサリー.children.create(name: 'カタログ/マニュアル')
自動車オートバイ_自動車アクセサリー.children.create(name: 'セキュリティ')
自動車オートバイ_自動車アクセサリー.children.create(name: 'ETC')
自動車オートバイ_自動車アクセサリー.children.create(name: 'その他')
自動車オートバイ_オートバイパーツ.children.create(name: 'タイヤ')
自動車オートバイ_オートバイパーツ.children.create(name: 'マフラー')
自動車オートバイ_オートバイパーツ.children.create(name: 'エンジン、冷却装置')
自動車オートバイ_オートバイパーツ.children.create(name: 'カウル、フェンダー、外装')
自動車オートバイ_オートバイパーツ.children.create(name: 'サスペンション')
自動車オートバイ_オートバイパーツ.children.create(name: 'ホイール')
自動車オートバイ_オートバイパーツ.children.create(name: 'シート')
自動車オートバイ_オートバイパーツ.children.create(name: 'ブレーキ')
自動車オートバイ_オートバイパーツ.children.create(name: 'タンク')
自動車オートバイ_オートバイパーツ.children.create(name: 'ライト、ウィンカー')
自動車オートバイ_オートバイパーツ.children.create(name: 'チェーン、スプロケット、駆動系')
自動車オートバイ_オートバイパーツ.children.create(name: 'メーター')
自動車オートバイ_オートバイパーツ.children.create(name: '電装系')
自動車オートバイ_オートバイパーツ.children.create(name: 'ミラー')
自動車オートバイ_オートバイパーツ.children.create(name: '外国オートバイ用パーツ')
自動車オートバイ_オートバイパーツ.children.create(name: 'その他')
自動車オートバイ_オートバイアクセサリー.children.create(name: 'ヘルメット/シールド')
自動車オートバイ_オートバイアクセサリー.children.create(name: 'バイクウエア/装備')
自動車オートバイ_オートバイアクセサリー.children.create(name: 'アクセサリー')
自動車オートバイ_オートバイアクセサリー.children.create(name: 'メンテナンス')
自動車オートバイ_オートバイアクセサリー.children.create(name: 'カタログ/マニュアル')
自動車オートバイ_オートバイアクセサリー.children.create(name: 'その他')
その他_ペット用品.children.create(name: 'ペットフード')
その他_ペット用品.children.create(name: '犬用品')
その他_ペット用品.children.create(name: '猫用品')
その他_ペット用品.children.create(name: '魚用品/水草')
その他_ペット用品.children.create(name: '小動物用品')
その他_ペット用品.children.create(name: '爬虫類/両生類用品')
その他_ペット用品.children.create(name: 'かご/おり')
その他_ペット用品.children.create(name: '鳥用品')
その他_ペット用品.children.create(name: '虫類用品')
その他_ペット用品.children.create(name: 'その他')
その他_食品.children.create(name: '菓子')
その他_食品.children.create(name: '米')
その他_食品.children.create(name: '野菜')
その他_食品.children.create(name: '果物')
その他_食品.children.create(name: '調味料')
その他_食品.children.create(name: '魚介類(加工食品)')
その他_食品.children.create(name: '肉類(加工食品)')
その他_食品.children.create(name: 'その他 加工食品')
その他_食品.children.create(name: 'その他')
その他_飲料酒.children.create(name: 'コーヒー')
その他_飲料酒.children.create(name: 'ソフトドリンク')
その他_飲料酒.children.create(name: 'ミネラルウォーター')
その他_飲料酒.children.create(name: '茶')
その他_飲料酒.children.create(name: 'ウイスキー')
その他_飲料酒.children.create(name: 'ワイン')
その他_飲料酒.children.create(name: 'ブランデー')
その他_飲料酒.children.create(name: '焼酎')
その他_飲料酒.children.create(name: '日本酒')
その他_飲料酒.children.create(name: 'ビール、発泡酒')
その他_飲料酒.children.create(name: 'その他')
その他_日用品生活雑貨旅行.children.create(name: 'タオル/バス用品')
その他_日用品生活雑貨旅行.children.create(name: '日用品/生活雑貨')
その他_日用品生活雑貨旅行.children.create(name: '洗剤/柔軟剤')
その他_日用品生活雑貨旅行.children.create(name: '旅行用品')
その他_日用品生活雑貨旅行.children.create(name: '防災関連グッズ')
その他_日用品生活雑貨旅行.children.create(name: 'その他')
その他_アンティークコレクション.children.create(name: '雑貨')
その他_アンティークコレクション.children.create(name: '工芸品')
その他_アンティークコレクション.children.create(name: '家具')
その他_アンティークコレクション.children.create(name: '印刷物')
その他_アンティークコレクション.children.create(name: 'その他')
その他_文房具事務用品.children.create(name: '筆記具')
その他_文房具事務用品.children.create(name: 'ノート/メモ帳')
その他_文房具事務用品.children.create(name: 'テープ/マスキングテープ')
その他_文房具事務用品.children.create(name: 'カレンダー/スケジュール')
その他_文房具事務用品.children.create(name: 'アルバム/スクラップ')
その他_文房具事務用品.children.create(name: 'ファイル/バインダー')
その他_文房具事務用品.children.create(name: 'はさみ/カッター')
その他_文房具事務用品.children.create(name: 'カードホルダー/名刺管理')
その他_文房具事務用品.children.create(name: 'のり/ホッチキス')
その他_文房具事務用品.children.create(name: 'その他')
その他_事務店舗用品.children.create(name: 'オフィス用品一般')
その他_事務店舗用品.children.create(name: 'オフィス家具')
その他_事務店舗用品.children.create(name: '店舗用品')
その他_事務店舗用品.children.create(name: 'OA機器')
その他_事務店舗用品.children.create(name: 'ラッピング/包装')
その他_事務店舗用品.children.create(name: 'その他')

# 送料テーブル
lady = Burden.create(:name=>"送料込み（出品者負担）")

lady.children.create(:name=>"未定")
lady.children.create(:name=>"らくらくメルカリ便")
lady.children.create(:name=>"ゆうメール")
lady.children.create(:name=>"普通郵便（定型、、定形外）")
lady.children.create(:name=>"クロネコヤマト")
lady.children.create(:name=>"ゆうパック")
lady.children.create(:name=>"クリップポスト")
lady.children.create(:name=>"ゆうパケット")

men = Burden.create(:name=>"着払い（購入者負担）")

men.children.create(:name=>"未定")
men.children.create(:name=>"クロネコヤマト")
men.children.create(:name=>"ゆうパック")
men.children.create(:name=>"ゆうメール")
